### ISSUE TITLE
windows下编译问题

### ISSUE THREAD

**Issue by Crazing** [sogou/srpc#115]
![图片](https://user-images.githubusercontent.com/17800062/139202900-8b3743cf-07f6-4aea-bf28-68064acb2f8c.png)
搞了一天了，心累。
昨天没看issues，没用vcpkg，自己按照依赖用cmake一个个编译的，最终编译到tutorial的时候报错，运行时库不匹配，改好之后又报错重定义。最后实在没办法就按照issues里用vcpkg装好了依赖，然后一步步编译workflow、srpc，最后又到了tutorial，这次又出了新问题。
说实话，真的不想用了，看起来依赖不多，编译起来问题一堆，我现在就一个想法，赶紧的毁灭吧

**Comment by ruoleng** [comment]
建议还是挂梯子用Vcpak 安装，省事很多。贴一份我64位的安装：
## 一、安装vcpkg

`cd D:\test`
`git clone https://github.com/microsoft/vcpkg.git`
`cd vcpkg`
`.\bootstrap-vcpkg.bat`

集成到VS中
`.\vcpkg integrate install`

注意：要安装VS的英文语言包，Vcpkg才能进行编译


## 二、安装srpc需要的包

`.\vcpkg.exe install zlib:x64-windows protobuf:x64-windows openssl:x64-windows workflow:x64-windows`

安装比较久，可以拆分成多个安装：

`.\vcpkg.exe install zlib:x64-windows`

`.\vcpkg.exe install protobuf:x64-windows`

`.\vcpkg.exe install openssl:x64-windows`

`.\vcpkg.exe install workflow:x64-windows`


## 三、安装srpc x64

### 使用vcpkg安装

`.\vcpkg.exe install srpc:x64-windows`
若安装后创建工程后，链接不成功，可以使用手动编译srpc的方式。


### 手动编译srpc

下载代码：
`cd D:\test`
`git clone https://github.com/sogou/srpc.git`

编译：

`cd D:\test\srpc`
`cmake -B cmbuild -S . -DCMAKE_TOOLCHAIN_FILE=D:\test\vcpkg\scripts\buildsystems\vcpkg.cmake`
`cmake --build cmbuild --config Debug`
`cmake --build cmbuild --config Release`


### 创建测试工程

在VS项目的的设置--vcpkg--General 里面的Use Vcpkg 设置为 是

(没有图床，图丢了，按照文字设置吧，很简单的)

按照SRPC的 Quick Start 进行Demo程序的创建。

创建的项目，项目设置：

include目录：*D:\test\srpc\\_include* 和 lib目录：*D:\test\srpc\\_lib*

C/C++ -- 命令行：/Zc:__cplusplus

链接器--输入：附加依赖项添加：*srpc.lib;ws2_32.lib;wsock32.lib;*


项目就可以编译链接成功，生成了。


## 四、编译tutorial

`cmake -B buildttr -S tutorial -DCMAKE_TOOLCHAIN_FILE=D:\test\vcpkg\scripts\buildsystems\vcpkg.cmake`
`cmake --build buildttr --config Debug`
`cmake --build buildttr --config Release`

上面的编译我自己编译时失败了，可能是thrift的问题，使用的是用cmake-gui生成工程后进行修改编译。

cmake-gui配置要自己一项一项配置库路径，直接使用vcpkg安装的库路径：

（没有图床，图丢了，就是把 D:\test\vcpkg\installed 里面的库路径填进去）

@Crazing
