### ISSUE TITLE
thrift桩代码生成工具生成的桩代码与期望不一样

### ISSUE THREAD

**Issue by qchenzi** [sogou/srpc#143]
此处使用了apache thrift提供的thrift文件（thrift后缀github文本编辑器不支持上传，所以换成了txt后缀）
[tutorial.txt](https://github.com/sogou/srpc/files/7759396/tutorial.txt)
[shared.txt](https://github.com/sogou/srpc/files/7759397/shared.txt)

使用srpc_generator生成后发现部分地方生成错误，如下图红框
<img width="945" alt="企业微信截图_52ebe79a-890e-42d2-9312-1548ffdc6e6b" src="https://user-images.githubusercontent.com/21999330/147022274-ee5ef423-6c59-4cbb-82b2-69b82875f1f9.png">

总结：出现如上错误的问题，我猜测是tutorial.thrift文件中的Struct Work下的num1赋了初始值0，导致代码生成工具没有成功识别
<img width="998" alt="wecom-temp-55d9af5a6d4522116b7655249faa16a1" src="https://user-images.githubusercontent.com/21999330/147022410-922f8fed-e5fd-42d5-9684-07200002f663.png">

**Comment by holmes1412** [comment]
看起来是解析时候错了，我们回头改一下～感谢小伙伴！

**Comment by Barenboim** [comment]
这个好像是我们解析器没有做赋初值的解析。另外还有个const xxx=xxx 也不支持。
我们这边可能要等元旦之后才有人手修复这个问题。

**Comment by qchenzi** [comment]
这里有个疑问补充一下哈，这里将thrift语法中enum枚举类型转换为int32是处于什么目的呢？
<img width="750" alt="企业微信截图_6f99b628-5ded-4441-81c2-246eb6d5fc88" src="https://user-images.githubusercontent.com/21999330/147198811-a1ca9d09-4c2d-4a1d-bfec-bb7d4aa62810.png">

**Comment by Barenboim** [comment]
@hihybin 
麻烦看看enum这个我们这么处理对不对。

**Comment by hihybin** [comment]
猜测这里用int32_t是为了实现简单些，thrift协议里会把enum作为int32_t处理，这里写int32_t不会对协议造成影响，暂时就不修改了

**Comment by Barenboim** [comment]
我重新提了这个parser的修改PR了。

**Comment by qchenzi** [comment]
printer改的不多，应该大佬直接拷贝一下就没问题了

**Comment by holmes1412** [comment]
@qchenzi 麻烦重新pull一下代码然后重新提一下pr哈～thrift语法你比较熟，printer你来改比较合适的～

**Comment by qchenzi** [comment]
好的哈，之前事情多给搞忘了
