### ISSUE TITLE
尝试将srpc集成到项目中，编译成功，运行时报错：undefined symbol: _ZTVN8protocol11HttpMessageE

### ISSUE THREAD

**Issue by Joeywzr** [sogou/srpc#144]
用c++filt解析结果为
> vtable for protocol::HttpMessage

系统为CentOS 7
ProtoBuf version：3.13.0
项目的CMakeLists.txt 如下，srpc编译好后，将include和静态链接库放入项目里

> set(SRPC_LIB srpc)
list(APPEND SRPC_INCLUDE_DIR
        ${ClickHouse_SOURCE_DIR}/contrib/srpc/_include
        ${ClickHouse_SOURCE_DIR}/contrib/srpc/workflow/_include
        )
dbms_target_link_libraries(PRIVATE ${SRPC_LIB})
dbms_target_include_directories(PRIVATE ${SRPC_INCLUDE_DIR})

请问可能是哪里出了问题呢？

**Comment by Barenboim** [comment]
set(SRPC_LIB srpc)
这里可能要加上workflow的lib。

**Comment by Barenboim** [comment]
你可以参考一下tutorial目录里的CMakeLists.txt

**Comment by Joeywzr** [comment]
好的！十分感谢！我试一下

**Comment by Joeywzr** [comment]
@Barenboim It works! 感谢！
