### ISSUE TITLE
linux中使用srpc的CMakelists写法

### ISSUE THREAD

**Issue by zmli6** [sogou/srpc#151]
hello！想问一下会出linux中使用srpc的CMakelists写法的示例吗？因为感觉现在CMakeLists还是挺常用的，作为刚刚开始学习这方面的新人感觉QuickStart还是有点不够用，如果能多几个示例就更好了:)

**Comment by holmes1412** [comment]
感谢小伙伴使用～目前可以参考tutorial目录下的Cmake，可以把示例中的可执行文件编译出来～
https://github.com/sogou/srpc/blob/master/tutorial/CMakeLists.txt
