### ISSUE TITLE
  文件传输的问题

### ISSUE THREAD

**Issue by Chingliu** [sogou/srpc#176]
你好，我们要将一个pdf转图片的程序改造成一个rpc服务。用户传入一个pdf,服务转换成图片传回。这数据量还是蛮大的，这样的场景srpc能支持吗？
另一个问题，像grpc它支持二进制然后它有许多第三方的语言绑定，那srpc我要实现以上的服务，如果用http感觉要编码转成文本开销是很大的，如果用tcp的话，其它语言如java等岂不是要实现一个客户端？

**Comment by Barenboim** [comment]
你好，文件传输不是什么大问题。数据发送之前，需要编码在内存里，除非文件非常大占过多内存，一般不会有什么问题。
我们确实只有C++实现。。。你可以先看看[workflow](https://github.com/sogou/workflow)的内容，底层原理都是在workflow项目，SRPC相当于是workflow上的几个RPC协议实现。

**Comment by Chingliu** [comment]
thanks
