### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by hanxi739** [sogou/srpc#197]
编译example时报错如下，请问是安装srpc过程中有什么问题吗，protobuf版本是3.19.4
![image](https://user-images.githubusercontent.com/37207162/161704302-00da7a37-1097-44ad-8248-fbd70944dc30.png)

**Comment by Barenboim** [comment]
你先到tutorial目录里make吧。模仿tutorial的做法，写个cmake。

**Comment by Barenboim** [comment]
我们在linux下的动态库产生有点问题，没有-l加上workflow和pb，你需要手动加一下。

**Comment by holmes1412** [comment]
已经把Readme.md上的编译命令改正了，参考这个issue：https://github.com/sogou/srpc/pull/199
感谢小伙伴～

**Comment by Barenboim** [comment]
你好，可以用新的代码再试一试了。如果是动态库，直接-lsrpc就可以了。

**Comment by Barenboim** [comment]
@hanxi739
