### ISSUE TITLE
vs2013是否能支持

### ISSUE THREAD

**Issue by mmtxcp** [sogou/srpc#202]
srpc使用了c++11标准，同时要求protobuf版本在3.12以上，是否是必须得？3.5版本是否可用？workflow也使用了c++11，但是vs2013仅支持部分，能否支持？

**Comment by holmes1412** [comment]
protobuf至少3.12是必须的，3.5有些接口不一样srpc会编译错误。

vs2013好像群里有其他小伙伴也用过，你可以试试～
