### ISSUE TITLE
thriftserver 多service 问题

### ISSUE THREAD

**Issue by mmtxcp** [sogou/srpc#204]
thriftserver 在具有多service情况下，调用失败，初步跟踪了下，把方法名称作为service 的name，导致find失败，始终返回一个。

**Comment by holmes1412** [comment]
你好，我们目前没有支持TMultiplexedProtocol和TMultiplexedProcessor，后续可以考虑支持上。如果你对这个协议了解的话也欢迎合作一起开发～o(∩_∩)o
