### ISSUE TITLE
后端实时推送数据到客户端的问题

### ISSUE THREAD

**Issue by guochaopeng** [sogou/srpc#210]
如果我要从后端实时推送数据到客户端，应用workflow的rpc框架，要怎么应用来做到实时推送呢

**Comment by Barenboim** [comment]
你可以在client端也开个srpc server的。连上server之后，把自己的ip port发过去。然后server端就可以rpc client啦。

**Comment by guochaopeng** [comment]
> 由于目前的rpc都是一来一回模式，因此想实现server主动推送到client，有一个最简单的方法是使用watch_timeout，这是对方第一次回复的超时，用法直接client.set_watch_timeout(60 * 1000 /* 60秒*/)，网络模型大概就是：
> 
> client发起task -------watch------> server干别的
> 
> client收到消息 <--------推送------ server发起推送 client再发起task-------watch------> server可以先干别的
> 
> client收到消息 <--------推送------ server发起推送

那这样就是要前端定时去请求，是吗

**Comment by holmes1412** [comment]
@guochaopeng 不是定期，是保持自己watch了就可以了。比如下次收到了推送，那你再watch一次。
当然我觉得楼上说的前端也悄悄开个server，让后端连上去，就可以被后端主动推送了，这个方案也挺好的。

**Comment by guochaopeng** [comment]
可以弄个案例吗？没有太理解

**Comment by guochaopeng** [comment]
> @guochaopeng 不是定期，是保持自己watch了就可以了。比如下次收到了推送，那你再watch一次。 当然我觉得楼上说的前端也悄悄开个server，让后端连上去，就可以被后端主动推送了，这个方案也挺好的。

可以弄个案例吗？没有太理解

**Comment by Barenboim** [comment]
其实，如果是server的主动推送，我们更推荐client端再开一个rpc server的方案。这个方案在我们公司内部大量应用，我认为是收缩rpc调用模型的一个好方法。

**Comment by guochaopeng** [comment]
> 其实，如果是server的主动推送，我们更推荐client端再开一个rpc server的方案。这个方案在我们公司内部大量应用，我认为是收缩rpc调用模型的一个好方法。

如果我的客户端不是使用的C端，而是使用的B端请求呢?

**Comment by lesismal** [comment]
可以考虑支持notify的功能，就是一方只发数据通知对方、不需要响应：
| Pattern | Interactive Directions       | Description              |
| ------- | ---------------------------- | ------------------------ |
| call    | two-way:<br>c -> s<br>s -> c | request and response     |
| notify  | two-way:<br>c -> s<br>s -> c | request without response |

我自己golang [arpc](https://github.com/lesismal/arpc)里就是这么搞的，然后就很多业务都能方便支持了，比如 IM、Game、Pushing Service 等等。

**Comment by lesismal** [comment]
> 也有用户帮我们魔改了完整的websocket client/server ，这个就是全双工。

tcp和websocket在作为rpc的传输载体协议时，没有本质区别。网络框架能支持并发call的，就能支持notify，跟传输载体协议的双工没什么直接关系，因为能支持并发call就意味着载体协议是双工，而且tcp和websocket也都是双工的。

**Comment by Barenboim** [comment]
> > 也有用户帮我们魔改了完整的websocket client/server ，这个就是全双工。
> 
> tcp和websocket在作为rpc的传输载体协议时，没有本质区别。网络框架能支持并发call的，就能支持notify，跟传输载体协议的双工没什么直接关系，因为能支持并发call就意味着载体协议是双工，而且tcp和websocket也都是双工的。

我们内部用得更多的，是自己也拍一个server下去。然后把自己的ip:port通过rpc告诉notify server。notify server通过正常的rpc访问client。其实我非常喜欢这种方式，很好的收缩了访问模型。

**Comment by lesismal** [comment]
> > > 也有用户帮我们魔改了完整的websocket client/server ，这个就是全双工。
> > 
> > 
> > tcp和websocket在作为rpc的传输载体协议时，没有本质区别。网络框架能支持并发call的，就能支持notify，跟传输载体协议的双工没什么直接关系，因为能支持并发call就意味着载体协议是双工，而且tcp和websocket也都是双工的。
> 
> 我们内部用得更多的，是自己也拍一个server下去。然后把自己的ip:port通过rpc告诉notify server。notify server通过正常的rpc访问client。其实我非常喜欢这种方式，很好的收缩了访问模型。
我们考虑两种业务：
第一种：仅限于集群内部不同服务之间的通信交互，虽然略麻烦、但这样用法是完全能满足需要的。
第二种：直接面向集群之外的用户，比如游戏服务之于玩家、电商服务之于买家、IM用户之于用户，我们不可能要求每个用户的client都启动一个非公网IP的server再用我们自己的server去connect每个用户的server。

作为通信通道，tcp也好websocket也好，单个连接信道本身就能满足上述集群内部和外部的全部需求。只是绝大多数rpc框架选择了被阉割的通信姿势，所以无法处理第二种业务。仅限于rpc，够用，无可厚非，但是还可以做到更好。

**Comment by holmes1412** [comment]
其实这个确实不是协议上的问题，是于核心通信器的默认模式相关。
我有写过一篇关于Workflow内部的网络优化点：[《C++ Workflow异步调度框架 - 性能优化网络篇》](https://zhuanlan.zhihu.com/p/484293077)，感兴趣可以看看～
Workflow的网络核心之所以可以这么快，核心通信器对连接的高效管理功不可没，所以默认用这种方式可以解决公司内大部分的问题。但正如你说的，开源了需求就多样化了起来，所以我们在尝试多种能同时完美兼容默认高效模式的方法去支持～

**Comment by Barenboim** [comment]
哈哈哈。是的。内部应用，我们尽量用简单模式。持续推送的话，目前workflow的server task有push接口，可以持续推送(同步写，超过tcp send buffer的数据需要用户自己配合timer重试)，但这个在rpc里没有实现。全双工，内部都支持，但一直没有我自己特别满意用户接口。所以暂时留给用户自己改😂





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月13日(周五) 晚上11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/srpc] 后端实时推送数据到客户端的问题 (Issue #210)




    
也有用户帮我们魔改了完整的websocket client/server ，这个就是全双工。
  
tcp和websocket在作为rpc的传输载体协议时，没有本质区别。网络框架能支持并发call的，就能支持notify，跟传输载体协议的双工没什么直接关系，因为能支持并发call就意味着载体协议是双工，而且tcp和websocket也都是双工的。
  
我们内部用得更多的，是自己也拍一个server下去。然后把自己的ip:port通过rpc告诉notify server。notify server通过正常的rpc访问client。其实我非常喜欢这种方式，很好的收缩了访问模型。
 我们考虑两种业务：
 第一种：仅限于集群内部不同服务之间的通信交互，虽然略麻烦、但这样用法是完全能满足需要的。
 第二种：直接面向集群之外的用户，比如游戏服务之于玩家、电商服务之于买家、IM用户之于用户，我们不可能要求每个用户的client都启动一个非公网IP的server再用我们自己的server去connect每个用户的server。
  
作为通信通道，tcp也好websocket也好，单个连接信道本身就能满足上述集群内部和外部的全部需求。只是绝大多数rpc框架选择了被阉割的通信姿势，所以无法处理第二种业务。仅限于rpc，够用，无可厚非，但是还可以做到更好。

**Comment by lesismal** [comment]
> 其实这个确实不是协议上的问题，是与核心通信器的默认模式相关。 我有写过一篇关于Workflow内部的网络优化点：[《C++ Workflow异步调度框架 - 性能优化网络篇》](https://zhuanlan.zhihu.com/p/484293077)，感兴趣可以看看～ Workflow的网络核心之所以可以这么快，核心通信器对连接的高效管理功不可没，所以默认用这种方式可以解决公司内大部分的问题。但正如你说的，开源了需求就多样化了起来，所以我们在尝试多种能同时完美兼容默认高效模式的方法去支持～

刚扫了几眼，有以下一些可以讨论下：

> 事件循环是通过eventfd或者其他方式打断epoll_wait来添加fd。显然，这个做法在很多场景下其实对性能是有影响的。
> 如果对一个的操作有变动，Workflow怎么做呢？我们会通过一个pipe事件通知这个poller thread。

其实极端点把eventfd或者pipe也是可以省略掉的，eventfd好像是每次要写大于等于8字节，pipe每次写1个字节就可以，pipe应该是比eventfd要省一点，但是仍然是syscall开销。
而epoll_ctl、close(fd)其实都是并发安全的，在其他线程去close，poller线程里的epoll fd也会把被其他线程close掉的fd自动清理掉、没什么副作用。我自己另外一个库 [nbio](https://github.com/lesismal/nbio) 就是这样做的，除了shutdown的时候用eventfd触发下，其他的epoll_ctl、close都是不用eventfd、pipe的。
golang标准库里好像是全局一个epoll fd管理所有fd的事件，也是用pipe来触发事件的增删改，因为golang的runtime需要结合整个调度相关，所以标准库这样做似乎是必须的。而我的nbio里没有标准库背上的包袱、只要跨协程的close处理好善后的清理、就可以了。所以我的nbio里应该是可以更节约一点syscall。但是因为新连接进来、写缓冲满或者close这些时候需要epoll_ctl，其他普通时候也是不需要去epoll_ctl的，所以节省的只是占比很小的一部分操作，对长连接高并发的吞吐量提高并不大。

**Comment by lesismal** [comment]
> 这里有个很重要的设计上的优化理念。
> Workflow从来不做空跑QPS之王，Workflow做的是一个跑得又快又稳的通用企业级框架，所以贯穿整个项目一个设计理念就是
> 面向全局优化：
> 即，比起尽可能优化一个请求得到最优性能，我们更倾向于优化整体的请求得到最优性能。
> 如果系统本身很忙，那么其实连进来的大部分fd都会比较繁忙，因此暂时还不需要去做考虑极端情况下的负载均衡，取模就够用了。毕竟每个优化步骤都是有点小开销，到底优化谁，这是个非常compromise的事情。

我跟你们这个观点是类似的，系统真忙起来，取模分散到各个线程去是足够的，如果系统不够繁忙，取模分散了，也不至于有哪个线程就瓶颈了。

但是仍然可以考虑另一种更加均衡的方案，比如单个epoll loop只处理事件、实际的IO交给其他线程。这当然就涉及到epoll不同mod的考虑了：
1. LT：事件来了传递给其他线程去处理读的话，如果读得慢于epoll loop，下一轮可能就重复派发事件了，这样会浪费，所以LT更适合在poller线程里直接读
2. ET：每次新数据来了会触发一次，如果本次IO线程循环读取尚未结束时，刚好有新数据到达缓冲区，则也会触发事件派发，IO线程循环读取完之后又收到event时可能会空读，也是一点浪费。但是这种情况占比比较小，大概可以忽略
3. ET+ONESHOT：可以避免事件的重复派发和空读，但是每次都要重新添加事件，正常情况下，这个syscall的成本相比其他两种方式性能明显要低一些，所以高性能的考量，基本放弃了这种

我自己框架的压测，LT性能略好些，所以我的框架默认用LT（也支持ET并且只需要一个配置项即可）、epoll loop的协程里直接读而不是在其他协程去处理读。但是上面的 2 可以作为一个IO线程均衡的方案，毕竟更均衡稳定、浪费的概率也不高。

**Comment by lesismal** [comment]
> 而Workflow的另一个不同点在于，它不是网络库，而是从网络模块到上层具体协议、任务流都有的成型框架。所以提供的接口语义并不是proactor、reactor，Workflow的语义是以消息为单位的。
> 为了简单起见，这里以收消息为例：
> Reactor是有事件来了，我告诉你，你负责去读出来；（epoll所提供的功能）
> Proactor是你给我一片内存，我把数据读出来了之后告诉你，一次通信的消息可能你是要读好几次才能读完的；（iocp，以及> 很多网络库的做法）
> Workflow是别管事件来了和读多少几次，我会帮你把你要的完整消息都收好了，再叫你；（也就是上层的每一个任务）

不知道我理解的对不对，`我会帮你把你要的完整消息都收好了，再叫你` 这里应该就是指 Workflow 已经处理好了消息包的编解码吧？其实websocket，或者其他的自定义tcp协议（游戏行业基本姿势），也都是如此的，直接提供的就是 OnMessage 之类的，回调给用户的数据就是一个完整消息包

**Comment by lesismal** [comment]
> 无论是client或者server，fd长期都保持EPOLLIN状态；
> 需要写数据时，先同步的写，如果数据可以全部写入tcp buffer，则无需改变fd的状态；
> 如果数据无法全部写入，通过epoll的MOD，原子性的把fd从EPOLLIN状态改为EPOLLOUT状态开始异步发送。
> 异步发送完成（fd会从epoll里删除），再把fd以EPOLLIN状态重新加入epoll。

这个应该是大家的常规用法，不算特别

**Comment by Barenboim** [comment]
我们的pipe是用于通知fd删除的，这个的使用范围极小，只是一些特殊情况下使用（比如对fd直接write失败，把fd从读事件删除），以及一些情况下server主动关闭keep-alive连接（正常keep-alive超时，也不使用这个方法）。所以整个正常运行过程不会用到pipe。pipe另一个作用，是通知程序退出的。所以，我们没有在pipe上浪费系统调用。所有对epoll或kqueue的操作，都是利用它的线程安全特征。你可以看看poller模块。
你的几个库star都好多啊！

**Comment by Barenboim** [comment]
我们对fd操作最复杂的部分是超时。全程通过一个timerfd和若干数据结构解决。EPOLL只使用了ET模式，方式上比较简单，方便和kqueue统一代码。

**Comment by lesismal** [comment]
> 我们的pipe是用于通知fd删除的，这个的使用范围极小，只是一些特殊情况下使用（比如对fd直接write失败，把fd从读事件删除），以及一些情况下server主动关闭keep-alive连接（正常keep-alive超时，也不使用这个方法）。所以整个正常运行过程不会用到pipe。pipe另一个作用，是通知程序退出的。所以，我们没有在pipe上浪费系统调用。所有对epoll或kqueue的操作，都是利用它的线程安全特征。你可以看看poller模块。 

我知道pipe是做这个用途的，但其实除了通知shutdown，其他还是可以省略掉的。。。我上面也提到过了，pipe的操作都只是占比很小的一部分操作，所以即使省掉也不会明显提高

> 你的几个库star都好多啊！

老铁你这是玩笑了，我的库的star相比于同类的 rpcx 和 gnet 那些几千起步的算是好少的了（尽管我的库性能基本是最好的、功能和易用性扩展性都是比同类的其他库多得多），不过我的库做的比较晚，去年才稍做宣传下，而且错过了国内golang论坛的好档期，现在那些论坛站长都去把精力花在公众号、卖课程赚钱上了，论坛用户也没几个人真正关注技术了，所以我这种新项目推广起来很难。不跟他们比star，就比性能和功能，吹个牛说，golang领域我的两个库截至目前都还没看到可以竞争的同类库。。。

**Comment by lesismal** [comment]
> 我们对fd操作最复杂的部分是超时。全程通过一个timerfd和若干数据结构解决。EPOLL只使用了ET模式，方式上比较简单，方便和kqueue统一代码。

刚好读到妹子发的帖子的timer的部分。timerfd够用了，另外还一种姿势是用timer队列的下一个超时时长作为epoll_wait的timeout。

**Comment by lesismal** [comment]
> 目前的超时算法利用了链表+红黑树的数据结构，时间复杂度在O(1)和O(logn)之间，其中n为网络线程的当前管理的fd数量。
> 超时处理目前看不是瓶颈所在，因为Linux内核epoll相关调用也是O(logn)时间复杂度，我们把超时都做到O(1)也区别不大。

堆应该是定时器领域更好一点的选择（因为空间亲和性、操作数应该是要好于红黑树的），不过nginx用了红黑树，libevent哪个版本来着好像是优化成了堆。整体性能差异倒是不大，都够用。

这里的O(1)我没有太理解，通常只有时间轮能做到O(1)，但是时间轮不精确。另外就是 `其中n为网络线程的当前管理的fd数量`，按理说，定时器的数量应该是大于fd数量的，因为同一个fd上可能有多个定时器，比如Call的超时可能小于读超时，所以此时可能存在两个超时，还可能有写超时。当然，同一个fd上的定时器数量可能不多，所以用链表管理同一个fd上的几个，也是相当于O(1)，这样确实是能做到某些操作设置定时器时，如果超时时间大于这个fd上已有的定时器超时时间，则只需要挂到链表后面就行、不需要再真正去设置到timerfd里，不知道我这样理解对不对

**Comment by Barenboim** [comment]
> > 我们的pipe是用于通知fd删除的，这个的使用范围极小，只是一些特殊情况下使用（比如对fd直接write失败，把fd从读事件删除），以及一些情况下server主动关闭keep-alive连接（正常keep-alive超时，也不使用这个方法）。所以整个正常运行过程不会用到pipe。pipe另一个作用，是通知程序退出的。所以，我们没有在pipe上浪费系统调用。所有对epoll或kqueue的操作，都是利用它的线程安全特征。你可以看看poller模块。
> 
> 我知道pipe是做这个用途的，但其实除了通知shutdown，其他还是可以省略掉的。。。我上面也提到过了，pipe的操作都只是占比很小的一部分操作，所以即使省掉也不会明显提高
> 
> > 你的几个库star都好多啊！
> 
> 老铁你这是玩笑了，我的库的star相比于同类的 rpcx 和 gnet 那些几千起步的算是好少的了（尽管我的库性能基本是最好的、功能和易用性扩展性都是比同类的其他库多得多），不过我的库做的比较晚，去年才稍做宣传下，而且错过了国内golang论坛的好档期，现在那些论坛站长都去把精力花在公众号、卖课程赚钱上了，论坛用户也没几个人真正关注技术了，所以我这种新项目推广起来很难。不跟他们比star，就比性能和功能，吹个牛说，golang领域我的两个库截至目前都还没看到可以竞争的同类库。。。

这么牛逼😳那必须看一看了。头条做了个netpoll是不是功能上和你有点类似？
Go上面做应用级的比较吃香。我一个同学做了dtm，还有个朋友搞了go-zero都star巨多。

**Comment by lesismal** [comment]
> 其实这个确实不是协议上的问题，是与核心通信器的默认模式相关。 我有写过一篇关于Workflow内部的网络优化点：[《C++ Workflow异步调度框架 - 性能优化网络篇》](https://zhuanlan.zhihu.com/p/484293077)，感兴趣可以看看～ Workflow的网络核心之所以可以这么快，核心通信器对连接的高效管理功不可没，所以默认用这种方式可以解决公司内大部分的问题。但正如你说的，开源了需求就多样化了起来，所以我们在尝试多种能同时完美兼容默认高效模式的方法去支持～

通篇大致扫完了，前面几楼是我的一些看法，不一定对，大家多多探讨

**Comment by lesismal** [comment]
> 

我这有一些benchmark，包括netpoll、gnet那些：
https://github.com/lesismal/go-net-benchmark/issues/1

但是，最好是自己跑压测代码或者自己写代码跑来看下，不要相信我也不要相信字节他们仓库自带的benchmark数据，以自己环境实测为准比较好，因为环境差异或者其他差异。。。

rpc框架的对比同样如此，不要相信仓库作者自带的benchmark数据，最好是自己实际跑代码看下为准。

因为考虑到自己仓库自带benchmark相当于自己既是运动员又是裁判员的问题，而且据我和阿里以及其他一些公司小伙伴实测的数据，感觉不同类型的一些仓库自带的数据不太准确，所以我自己的两个仓库里都没有去自带，而是提供三方或者自己的benchmark代码，鼓励用户自己环境实测为准。

**Comment by Barenboim** [comment]
> > 目前的超时算法利用了链表+红黑树的数据结构，时间复杂度在O(1)和O(logn)之间，其中n为网络线程的当前管理的fd数量。
> > 超时处理目前看不是瓶颈所在，因为Linux内核epoll相关调用也是O(logn)时间复杂度，我们把超时都做到O(1)也区别不大。
> 
> 堆应该是定时器领域更好一点的选择（因为空间亲和性、操作数应该是要好于红黑树的），不过nginx用了红黑树，libevent哪个版本来着好像是优化成了堆。整体性能差异倒是不大，都够用。
> 
> 这里的O(1)我没有太理解，通常只有时间轮能做到O(1)，但是时间轮不精确。另外就是 `其中n为网络线程的当前管理的fd数量`，按理说，定时器的数量应该是大于fd数量的，因为同一个fd上可能有多个定时器，比如Call的超时可能小于读超时，所以此时可能存在两个超时，还可能有写超时。当然，同一个fd上的定时器数量可能不多，所以用链表管理同一个fd上的几个，也是相当于O(1)，这样确实是能做到某些操作设置定时器时，如果超时时间大于这个fd上已有的定时器超时时间，则只需要挂到链表后面就行、不需要再真正去设置到timerfd里，不知道我这样理解对不对

首先，我们一个fd上最多一个超时(也可无超时)。一个fd同时需要关注读写的话，必须通过dup操作多产生一个fd放进去。
另外，我们的数据结构是rbtree+list。因为超时时间总是倾向于增大(绝对时间)，所以会先对比list最后一个node的超时，如果比这个大就放在list，否则放在tree。放tree的时候，也优先对比tree的最大节点。
整体下来，大多数操作都是O(1)。

**Comment by lesismal** [comment]
> go-zero都star巨多

说实话，国内的技术圈子，实在有点不好意思喷了。小白太多，只要有个圈子就互相吹捧。
举个例子：
https://github.com/zeromicro/go-zero/blob/master/core/hash/hash.go#L24
这里的用标准库的hex，性能要略好的，用fmt不知道是出于秀功夫还是作者真就不懂。。。

再举个例子：
https://github.com/zeromicro/go-zero/tree/master/core/codec
这个包名叫codec，里面放的是一些加密算法和压缩相关，我通常理解的codec是json、pb或者比如自定义的包解析比如流媒体编解码或者你们Workflow完整包的编解码，这些内容放到codec里我觉得都是合理的，但是加密算法、压缩放到个叫做codec的包里，codec翻译过来是编解码器，尤其是他们这个codec包里还有hmac，我倒是想知道他们是怎么把它解码的。。。

**Comment by lesismal** [comment]
> 因为超时时间总是倾向于增大(绝对时间)

这个确实，甚至像读写超时因为所有fd的同一种超时时间都是相同的、后加进去的定时器肯定大于前面的，所以这些不同种类的超时分开用不同的list，每次把之前list node remove然后append到尾巴就行了，肯定是O(1)

**Comment by lesismal** [comment]
清理了一波，免得喧宾夺主。本条后续也会清理掉

**Comment by Barenboim** [comment]
> 清理了一波，免得喧宾夺主。本条后续也会清理掉

哈哈，其实没事，都是讨论技术。我也可以hide回复。

**Comment by lyla105** [comment]
> 由于目前的rpc都是一来一回模式，因此想实现server主动推送到client，有一个最简单的方法是使用watch_timeout，这是对方第一次回复的超时，用法直接client.set_watch_timeout(60 * 1000 /* 60秒*/)，网络模型大概就是：
> 
> client发起task -------watch------> server干别的
> 
> client收到消息 <--------推送------ server发起推送 client再发起task-------watch------> server可以先干别的
> 
> client收到消息 <--------推送------ server发起推送

我想请教下，这个srpc跟grpc的区别？
这里说srpc的rpc是一来一回的模式，是对应的grpc的简单模式么？
grpc的流模式，srpc没有对应的实现，是么？

**Comment by Barenboim** [comment]
嗯嗯，我们没有主动推送的功能啊。workflow里也只支持到SSE模式。

想做推送可以两边都开server，互相调用，actor模式。我们本质上就是actor。

**Comment by lyla105** [comment]
> 嗯嗯，我们没有主动推送的功能啊。workflow里也只支持到SSE模式。
> 
> 想做推送可以两边都开server，互相调用，actor模式。我们本质上就是actor。

好的，谢谢~
