### ISSUE TITLE
Windows下的编译问题

### ISSUE THREAD

**Issue by luciouskami** [sogou/srpc#216]
在windows 10 VS2022环境下编译。
按照几个Issue里面的步骤尝试了一下，出现了以下错误：
![1](https://user-images.githubusercontent.com/10268785/168551851-7505bfbd-cf9a-494a-b22b-f9bf066b5b18.jpg)
![2](https://user-images.githubusercontent.com/10268785/168552358-6d81600d-d119-453c-8893-24fbe935284e.jpg)

这几个头文件应该是windows下没有的
#ifndef WIN32 这样的操作肯定是不行的，请问应该怎么样修改才能编译成功呢？

**Comment by Barenboim** [comment]
请切到Windows分支。主分支只支持unix环境！

**Comment by holmes1412** [comment]
应该是我在rpc_module_span.h里没注意区分不同系统的头文件。我改一下～

**Comment by luciouskami** [comment]
> 请切到Windows分支。主分支只支持unix环境！

sprc好像没有windows分支..

**Comment by luciouskami** [comment]
> 应该是我在rpc_module_span.h里没注意区分不同系统的头文件。我改一下～
好的，谢谢

**Comment by Barenboim** [comment]
不好意思，我看错了，以为是workflow的issue😂

**Comment by luciouskami** [comment]
> 不好意思，我看错了，以为是workflow的issue😂

没关系。您的响应速度好快！我第一次见到那么快的响应速度。

**Comment by holmes1412** [comment]
一般这种都是猪队友的锅QWQ这个commit里已改～https://github.com/sogou/srpc/commit/6d725bc0dc26b616272bdf92aab04e88628a43e7
感谢 @luciouskami ，还发现问题欢迎随时联系我们，喜欢的话提PR也可～

**Comment by luciouskami** [comment]
> 一般这种都是猪队友的锅QWQ这个commit里已改～[6d725bc](https://github.com/sogou/srpc/commit/6d725bc0dc26b616272bdf92aab04e88628a43e7) 感谢 @luciouskami ，还发现问题欢迎随时联系我们，喜欢的话提PR也可～

非常感谢！

**Comment by luciouskami** [comment]
好像还有一个点

srpc\src\generator\parser.cc

这么改符合规范吗？
```c++
#include <ctype.h>
#include "parser.h"
#include "thrift/rpc_thrift_enum.h"
#include <sys/types.h>

#ifdef _MSC_VER
#define MAXPATHLEN 260
#include <direct.h>
#else
#include <arpa/inet.h>
#endif
```

**Comment by Barenboim** [comment]
这个MAXPATHLEN好像一直都这么写，之前没有人报过问题。MSVC下编译不通过吗？

**Comment by holmes1412** [comment]
我查了下，两个flag的含义差别是比如：
- _WIN32 是判断是否构建在Windows平台上
- _MSC_VER 是用来判断是否是微软的编译器

感觉其实差不多哈。然后我查了下我们依赖的一些压缩库，确实使用`_MSC_VER` 来判断的会多一些～

**Comment by Barenboim** [comment]
我几个判断吧。这个MAXPATHLEN我真不知到什么标准。

**Comment by holmes1412** [comment]
> 这个MAXPATHLEN好像一直都这么写，之前没有人报过问题。MSVC下编译不通过吗？

SRPC一般高手才手编源码，其他人可能都在用vcpkg的旧版本😂就没有发现过

**Comment by Barenboim** [comment]
https://github.com/sogou/srpc/pull/217
我加了这个检测

**Comment by Barenboim** [comment]
> > 这个MAXPATHLEN好像一直都这么写，之前没有人报过问题。MSVC下编译不通过吗？
> 
> SRPC一般高手才手编源码，大部分小伙伴可能都在用vcpkg的旧版本😂就没有发现过

这个不应该吧，我都不知道这个什么时候引入的。另外，这种没谱的常量，不要乱用啊。

**Comment by holmes1412** [comment]
以前修复生成代码前缀路径的时候不小心引入的：https://github.com/sogou/srpc/commit/cd9c2fe1638bd52933d2136c2a99c1bb9032e4f7

这个可以自己随便定义一个长度就好，可以不用这个变量。

**Comment by holmes1412** [comment]
@luciouskami 要不你按你一开始的改动，直接定义一个MAXPATHLEN比如4096给我们提个PR就好哈，顺便也可以帮我们看看是否还有其他编译不过的地方

感谢！！！

P.S. 暂时统一用_WIN32判断吧，以后有需要的话统一改一下。

**Comment by Barenboim** [comment]
@luciouskami
你好，我感觉这个文件写的不对。unistd.h Windows下也没有。能不能帮我们改一下？不用MAXPATHLEN了，直接写4096吧。

**Comment by luciouskami** [comment]
> 



> @luciouskami 你好，我感觉这个文件写的不对。unistd.h Windows下也没有。能不能帮我们改一下？不用MAXPATHLEN了，直接写4096吧。

好 我这就改下

**Comment by luciouskami** [comment]
```c++
#include <ctype.h>
#include "parser.h"
#include "thrift/rpc_thrift_enum.h"

#ifndef _WIN32
#include <unistd.h>
#include <sys/param.h>
#else
#define MAXPATHLEN 4096
#include <direct.h>
#endif
```

我改成了上面这种形式

**Comment by Barenboim** [comment]
> ```c++
> #include <ctype.h>
> #include "parser.h"
> #include "thrift/rpc_thrift_enum.h"
> 
> #ifndef _WIN32
> #include <unistd.h>
> #include <sys/param.h>
> #else
> #define MAXPATHLEN 4096
> #include <direct.h>
> #endif
> ```
> 
> 我改成了上面这种形式 编译是能通过的，但是tutorial的编译好像还是有点问题，不过这个问题不大了。

Tutorial是什么问题呢？可以发一下

**Comment by luciouskami** [comment]
> > ```c++
> > #include <ctype.h>
> > #include "parser.h"
> > #include "thrift/rpc_thrift_enum.h"
> > 
> > #ifndef _WIN32
> > #include <unistd.h>
> > #include <sys/param.h>
> > #else
> > #define MAXPATHLEN 4096
> > #include <direct.h>
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我改成了上面这种形式 编译是能通过的，但是
> >         
> >           tutorial
> >           (教程)
> >         
> >         的编译好像还是有点问题，不过这个问题不大了。
> 
> Tutorial (教程) 是什么问题呢？可以发一下

用CMAKE生成项目提示：
CMake Error at E:/GitHubProjects/srpc/srpc-config.cmake:11 (message):
  File or directory E://tools/srpc referenced by variable SRPC_BIN_DIR does not exist !

**Comment by luciouskami** [comment]
根据srpc-config.cmake中的：
set_and_check(SRPC_BIN_DIR "${PACKAGE_PREFIX_DIR}/tools/srpc")
且根据上文的报错信息，这个SRPC_BIN_DIR指向的应该是install的路径？

**Comment by luciouskami** [comment]
> 发现了，应该是CMakeLists.txt中的102行，把这个值改过：
> 
> ```c++
> if(NOT VCPKG_TOOLCHAIN)                                                            
>     set(CONFIG_BIN_DIR ${BIN_DIR})                                                 
> else()                                                                             
>     set(CONFIG_BIN_DIR ${CMAKE_INSTALL_PREFIX}/tools/srpc)                         
> endif()
> ```
> 
> 这部分是原先另一个Windows同学帮我们改的。

emmm，我先试一下。这个改法感觉有点瑕疵呀，用VCPKG_TOOLCHAIN作为判断依据有一些不准确，因为vcpkg可能仅仅只安装一些依赖项，这个写法应该是使用vcpkg安装 srpc的时候才能正常工作，大概是这样子？

**Comment by luciouskami** [comment]
![1](https://user-images.githubusercontent.com/10268785/168591512-67c09335-d83b-4204-9018-32af03a7bfce.jpg)
然后，把105行的代码改成set(CONFIG_BIN_DIR ${BIN_DIR}) 以后可以生成vs工程，但是编译的时候会报上面几个错误，我打开vs工程看了一下，好像根本没引用那几个库。。

**Comment by holmes1412** [comment]
你说的对，原先那个Windows同学改的意思应该是：如果通过vcpkg安装的话，那么库libsrpc.dll 和工具srpc_generator是通过vcpkg安装到了`tools/srpc/`这个目录下，而不是我们手动编译时的`E:\GitHubProjects\srpc\`。这么判断确实是不太准确的。

另外srpc的压缩是需要lz4和snappy的，源码编译的时候，应该在third_party目录下有～vcpkg的安装可能是直接安装了

**Comment by luciouskami** [comment]
> 你说的对，原先那个Windows同学改的意思应该是：如果通过vcpkg安装的话，那么库libsrpc.dll 和工具srpc_generator是通过vcpkg安装到了`tools/srpc/`这个目录下，而不是我们手动编译时的`E:\GitHubProjects\srpc\`。这么判断确实是不太准确的。
> 
> 另外srpc的压缩是需要lz4和snappy的，源码编译的时候，应该在third_party目录下有～vcpkg的安装可能是直接安装了
> 
> 是不是`tutorial/CMakeLists.txt`这里的WIN32下忘记链接这俩了:
> 
> ```shell
> 104 if (APPLE)                                                                      
> 105     set(SRPC_LIB srpc workflow pthread OpenSSL::SSL OpenSSL::Crypto protobuf z) 
> 106 elseif (WIN32)                                                                  
> 107     set(SRPC_LIB srpc workflow ws2_32 wsock32 OpenSSL::SSL OpenSSL::Crypto protobuf::libprotobuf ZLIB::ZLIB)
> 108 else ()                                                                         
> 109     set(SRPC_LIB srpc workflow pthread OpenSSL::SSL OpenSSL::Crypto protobuf z ${SNAPPY_LIB} ${LZ4_LIB})
> 110 endif ()                                                                        
> ```

应该是这样，我手动在工程中引用了这两个lib以后编译成功了。。

**Comment by holmes1412** [comment]
不是简单地加在后面就可以？
set(SRPC_LIB srpc workflow ws2_32 wsock32 OpenSSL::SSL OpenSSL::Crypto protobuf::libprotobuf ZLIB::ZLIB Snappy Lz4) # 之类的？

总之非常感谢帮忙验证！！！如果后续有好的建议的话也期待随时提出～

**Comment by luciouskami** [comment]
> 不是简单地加在后面就可以？ set(SRPC_LIB srpc workflow ws2_32 wsock32 OpenSSL::SSL OpenSSL::Crypto protobuf::libprotobuf ZLIB::ZLIB Snappy Lz4) # 之类的？
> 
> 总之非常感谢帮忙验证！！！如果后续有好的建议的话也期待随时提出～

emmm我是说之前那一步，105行那个
set(CONFIG_BIN_DIR ${CMAKE_INSTALL_PREFIX}/tools/srpc)       
如果说用vcpkg安装的话，应该怎么准一些，这个意思
后面的那个确实只要加上就行了。

**Comment by holmes1412** [comment]
有道理～那我加个判断～>_<

**Comment by luciouskami** [comment]
> 有道理～那我加个判断～>_<

感觉windows下编译有点乱，理论上加上那两个库应该能直接编译通过：
![image](https://user-images.githubusercontent.com/10268785/168600450-c56a0aad-4709-4ff1-816d-f120dc540cc2.png)
然而我打印了一下发现${SNAPPY_LIB}和${LZ4_LIB}都是空的，看了以前的几个issue说是改用了vcpkg没用third_party下面的了，emmm，这部分应该也要改下。

**Comment by holmes1412** [comment]
这个应该是以前，没有同时编译动态库和静态库的原因（以前为了兼容线上，做法是编译静态库，并且做了个libsrpc.so作为链接脚本，用GROUP ... AS_NEEDED的方式去链libsrpc.a）。

现在已经动态库和静态库都编译了（至少在linux和mac确认是），然后一般是有动态库的话就优先依赖动态库。

是希望tutorial里cmake有-D选项去指定是否依赖静态库？我研究下怎么弄～

**Comment by luciouskami** [comment]
> 这个应该是以前，没有同时编译动态库和静态库的原因（以前为了兼容线上，linux下做法是编译静态库，并且做了个libsrpc.so作为链接脚本，用GROUP ... AS_NEEDED的方式去链libsrpc.a，而mac下就只有静态库）。
> 
> 
> 
> 现在已经动态库和静态库都编译了（至少在linux和mac确认是），然后一般是有动态库的话就优先依赖动态库。
> 
> 
> 
> 是希望tutorial里cmake有-D选项去指定是否依赖静态库？我研究下怎么弄～

嗯，这个可能也需要。我用词不太准确。上面说的是运行时来着，就是c++的运行时   runtime=static或者shard

**Comment by holmes1412** [comment]
了解了，是希望编译srpc找workflow或protobuf的路径始终与runtime=static或者shared的时候一致。感谢细心的提议，我明天确认一下～

**Comment by luciouskami** [comment]
> 了解了，是希望编译srpc找workflow或protobuf的路径始终与runtime=static或者shared的时候一致。感谢细心的提议，我明天确认一下～

嗯，我看没有提供开关的样子（可能是我看的不仔细）？

**Comment by luciouskami** [comment]
add feature on #220
