### ISSUE TITLE
请问srpc对于Stream数据有什么好的解决方案吗

### ISSUE THREAD

**Issue by superyuxiao** [sogou/srpc#230]
比如server需要返回好多条的message的场景下，使用gRPC的streaming RPC就可以。请问使用srpc有什么好的方法实现吗？

**Comment by Barenboim** [comment]
你好，这个是srpc的短板……确实没有实现streaming通信。
workflow项目，server倒是有push接口，可以多次回包，但srpc里没有把这个支持上。
workflow里对多次回包的支持，你可以看一下这个issue：https://github.com/sogou/workflow/issues/929#issuecomment-1144666820
srpc需要在协议层支持，比较复杂。
