### ISSUE TITLE
如何使用srpc中的文件压缩功能

### ISSUE THREAD

**Issue by AndrewAndJenny** [sogou/srpc#232]
作者大大您好:目前我想用workflow实现客户端文件压缩传输的功能，当前主要是先完成批量文件下载的功能。
主要思路为利用ParallelWork和SeriesWork，在串行流中根据第一个httptask获取服务器中文件大小，文件超出阈值则在串行流中增加后续httptask分块下载，SeriesWork的callback中进行文件完整性检验与合并。
但是workflow中并不支持文件压缩的功能，srpc中是有这样的能力的，但是我不太懂rpc，所以想问问有没有什么小示例来解决我的疑惑，同时作为一个网络服务初学者，想请您咨询一下我的思路有没有啥问题，希望能获得您的帮助！

**Comment by AndrewAndJenny** [comment]
非常感谢您百忙之中给我回复问题，实际的情况是这样的:
服务端是部署的简单对象存储（其他组的服务，我只能进行http请求文件压缩传输，比如gzip，然后客户端收到响应进行解压缩后存储），不知道这样的情况下还能用到咱们srpc中的压缩功能吗

**Comment by AndrewAndJenny** [comment]
尊敬的作者大大，我看到了chanchan基于workflow写的wfrest里有个gzip压缩/解压缩的功能，我想可以先参考他的实现方法去做我说的事

**Comment by Barenboim** [comment]
你好。感觉这个问题，和rpc没有关系。用workflow发一个gzip压缩请求不就好了？收到回复也解压一下。感觉这个完全可以框架之外做。
另外，可以参考一下基于workflow的wfrest项目：https://github.com/wfrest/wfrest
wfrest是有处理压缩的，但主要做server。

**Comment by Barenboim** [comment]
wfrest里有个例子，使用workflow发gzip压缩的http请求，你可以看一下：
https://github.com/wfrest/wfrest/blob/main/docs/cn/compress.md

**Comment by AndrewAndJenny** [comment]
> wfrest里有个例子，使用workflow发gzip压缩的http请求，你可以看一下： https://github.com/wfrest/wfrest/blob/main/docs/cn/compress.md

非常感谢您的回复，我当时就是看到srpc支持很多种压缩方式，所以才突发奇想有了这个issue，再次感谢您的帮助！

**Comment by Barenboim** [comment]
不客气的。你看看能不能解决你的需求。有任何别的问题随时沟通。

**Comment by Barenboim** [comment]
我发现在我回复之前，你已经找到了wfrest了😄

**Comment by AndrewAndJenny** [comment]
> 我发现在我回复之前，你已经找到了wfrest了😄

非常感谢您和22姐大晚上回复我！
workflow是个非常优秀的框架，借助它，让我这个小白能快速实现我想做的功能，后面我会努力学习其中的设计思想！

**Comment by AndrewAndJenny** [comment]
之前说的那个功能我已经实现了，速度还挺快，这个issue我就关啦

**Comment by AndrewAndJenny** [comment]
> > 之前说的那个功能我已经实现了，速度还挺快，这个issue我就关啦
> 
> 嗯嗯，能解决问题就太好了！你好像忘了star workflow项目😂。

尴尬了啊，这回我点了。。。 :smile:

**Comment by Barenboim** [comment]
> > > 之前说的那个功能我已经实现了，速度还挺快，这个issue我就关啦
> > 
> > 
> > 嗯嗯，能解决问题就太好了！你好像忘了star workflow项目😂。
> 
> 尴尬了啊，这回我点了。。。 😄

使用愉快哈。有问题随时发issue！
