### ISSUE TITLE
Thrift Union 支持

### ISSUE THREAD

**Issue by redkongdong** [sogou/srpc#249]
请问现在thrift idl 里边定义union是支持的吗？

我试了定义的并没有被解析出来生成对应代码

**Comment by Barenboim** [comment]
有可能。我们加一下。这个好像和struct在解析上没有什么区别吧？

**Comment by redkongdong** [comment]
应该差不多

**Comment by Barenboim** [comment]
支持上了。试了一下，在thrift里，union就是struct的一个别名，产生的c++代码是一模一样的。

**Comment by redkongdong** [comment]
感恩
