### ISSUE TITLE
srpc在C++20的编译问题

### ISSUE THREAD

**Issue by yyaxxx** [sogou/srpc#255]
这3个地方的模板参数是多余的吧? c++20会编译报错"error: expected unqualified-id before ')' token"
https://github.com/sogou/srpc/blob/39678c2d1be4bd20fd2e9565fb52959ff528d321/src/thrift/rpc_thrift_idl.h#L86
https://github.com/sogou/srpc/blob/39678c2d1be4bd20fd2e9565fb52959ff528d321/src/thrift/rpc_thrift_idl.inl#L53
https://github.com/sogou/srpc/blob/39678c2d1be4bd20fd2e9565fb52959ff528d321/src/thrift/rpc_thrift_idl.inl#L674

**Comment by Barenboim** [comment]
是的，继承的时候不用加模板参。我来改一下。

**Comment by Barenboim** [comment]
好了，看看这个PR。多谢。

**Comment by Barenboim** [comment]
@yyaxxx 
顺便改了这个：
https://github.com/sogou/workflow/pull/1020
