### ISSUE TITLE
Windows环境内存增涨问题

### ISSUE THREAD

**Issue by j05070415** [sogou/srpc#262]
#include <QCoreApplication>
#include <QDebug>
#include <QtConcurrent/QtConcurrent>

#include "echo_pb.srpc.h"
#include "srpc/rpc_types.h"
#include "workflow/WFFacilities.h"

class ExampleServiceImpl : public Example::Service
{
public:
    void Echo(EchoRequest *req, EchoResponse *resp, srpc::RPCContext *ctx) override
    {
//        ctx->set_compress_type(srpc::RPCCompressLz4);
        resp->set_message("%d", req->GetCachedSize());

//        printf("Server Echo()\nget_req:\n%s\nset_resp:\n%s\n",
//                req->DebugString().c_str(), resp->DebugString().c_str());
    }
};

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QtConcurrent::run([](){
        srpc::SRPCServer server;
        ExampleServiceImpl impl;

        server.add_service(&impl);

        if (server.start(1412) == 0) {
            qDebug() << "start sucess!";
        } else {
            qDebug() << "start failed!";
        }
        WFFacilities::WaitGroup group(1);
        group.wait();
    });

    Example::SRPCClient client("127.0.0.1", 1412);
    srpc::RPCTaskParams *par = (srpc::RPCTaskParams *)client.get_task_params();
//    par->compress_type = srpc::RPCCompressLz4;
    int counter = 0;
    while (true) {
        EchoRequest req;
        req.set_name("123123");
        std::string data(8192, '\0');
        *(req.mutable_message()) = data;
//        client.Echo(&req, [](EchoResponse* resp, srpc::RPCContext* ctx){
//            if (ctx->success())
//                qDebug() << "sucess " << resp->message().c_str();
//            else
//                qDebug() << "failure " << ctx->get_errmsg();
//        });

        auto future = client.async_Echo(&req);
        auto res = future.get();
        qDebug() << "res:" << res.first.message().c_str() << ++counter;// << res.second.success();

//        EchoResponse sync_resp;
//        srpc::RPCSyncContext sync_ctx;
//        client.Echo(&req, &sync_resp, &sync_ctx);

//        if (sync_ctx.success)
//            printf("scuss %s\n", sync_resp.DebugString().c_str());
//        else {
//            printf("failure:%s\n", sync_ctx.errmsg.c_str());
//        }
    }
    return a.exec();
}

**Comment by Barenboim** [comment]
好像是半同步用法的问题……
async_Echo里new出出来的promise，没有人delete。可能用半同步的不多，没有人发现这个问题😓
我看看怎么改好一点。

**Comment by Barenboim** [comment]
暂未发现有什么问题。刚才以为是半同步的bug，仔细看了看，好像也没有问题。
这个代码是运行在Linux吗？我一会用valgrind跑一下。

**Comment by holmes1412** [comment]
我试了下，没有内存泄露的情况～比较怀疑是你在使用pb的mutable_xxx等接口等时候产生的，因为涉及pb的代码编译不过，只能改了之后才能编译过，可以检查一下。

promise在async_request函数的包了一层的callback里会delete，可以参考workflow项目的[manager/WFFacilities.inl](https://github.com/sogou/workflow/blob/master/src/manager/WFFacilities.inl)：

~~~cpp
template<class REQ, class RESP>                                                 
WFFuture<WFFacilities::WFNetworkResult<RESP>> WFFacilities::async_request(TransportType type, const std::string& url, REQ&& req, int retry_max){                                                                               
    ParsedURI uri;                                                              
    auto *pr = new WFPromise<WFNetworkResult<RESP>>();                          
    auto fr = pr->get_future();                                                 
    auto *task = new WFComplexClientTask<REQ, RESP>(retry_max, [pr](WFNetworkTask<REQ, RESP> *task) {
        WFNetworkResult<RESP> res;                                              
                                                                                
        res.seqid = task->get_task_seq();                                       
        res.task_state = task->get_state();                                     
        res.task_error = task->get_error();                                     
        if (res.task_state == WFT_STATE_SUCCESS)                                
            res.resp = std::move(*task->get_resp());                            
                                                                                
        pr->set_value(std::move(res));                                          
        delete pr;                                                              
    });                                                                         
    ...                                                              
} 
~~~

**Comment by j05070415** [comment]
> 暂未发现有什么问题。刚才以为是半同步的bug，仔细看了看，好像也没有问题。 这个代码是运行在Linux吗？我一会用valgrind跑一下。

win7 64，proto 3.21.4
![image](https://user-images.githubusercontent.com/7128724/189508477-4afb2c88-7605-41b5-9f2e-38eec7d226a5.png)

**Comment by j05070415** [comment]
> > 暂未发现有什么问题。刚才以为是半同步的bug，仔细看了看，好像也没有问题。 这个代码是运行在Linux吗？我一会用valgrind跑一下。
> 
> win7 64，proto 3.21.4 ![image](https://user-images.githubusercontent.com/7128724/189508477-4afb2c88-7605-41b5-9f2e-38eec7d226a5.png)

这是我的proto文件，使用proto3，
syntax="proto3";

message EchoRequest {
	bytes message = 1;
	string name = 2;
};

message EchoResponse {
	bytes message = 1;
	int32 state = 2;
	int32 error = 3;
};

service Example {
	rpc Echo(EchoRequest) returns (EchoResponse);
};

**Comment by Barenboim** [comment]
Windows下srpc代码是一样的。如果说有问题，那只能是workflow代码了。我们这边没有Windows的调试环境，您能不能帮我们查一下？

**Comment by j05070415** [comment]
> 我试了下，没有内存泄露的情况～比较怀疑是你在使用pb的mutable_xxx等接口等时候产生的，因为涉及pb的代码编译不过，只能改了之后才能编译过，可以检查一下。
> 
> promise在async_request函数的包了一层的callback里会delete，可以参考workflow项目的[manager/WFFacilities.inl](https://github.com/sogou/workflow/blob/master/src/manager/WFFacilities.inl)：
> 
> ```c++
> template<class REQ, class RESP>                                                 
> WFFuture<WFFacilities::WFNetworkResult<RESP>> WFFacilities::async_request(TransportType type, const std::string& url, REQ&& req, int retry_max){                                                                               
>     ParsedURI uri;                                                              
>     auto *pr = new WFPromise<WFNetworkResult<RESP>>();                          
>     auto fr = pr->get_future();                                                 
>     auto *task = new WFComplexClientTask<REQ, RESP>(retry_max, [pr](WFNetworkTask<REQ, RESP> *task) {
>         WFNetworkResult<RESP> res;                                              
>                                                                                 
>         res.seqid = task->get_task_seq();                                       
>         res.task_state = task->get_state();                                     
>         res.task_error = task->get_error();                                     
>         if (res.task_state == WFT_STATE_SUCCESS)                                
>             res.resp = std::move(*task->get_resp());                            
>                                                                                 
>         pr->set_value(std::move(res));                                          
>         delete pr;                                                              
>     });                                                                         
>     ...                                                              
> } 
> ```

1.不使用message任何接口也是会泄露，发现使用TRPCServer服务和TRPCClient客户端内存能控制住

**Comment by holmes1412** [comment]
> 1.不使用message任何接口也是会泄露，发现使用TRPCServer服务和TRPCClient客户端内存能控制住

明白了，那应该不是pb使用的问题，目前比较怀疑是workflow的windows kernel的问题，因为我试过和你一样的半同步接口，在linux下没有复现。

两个问题请教一下哈：
1. 使用trpc server的时候，也是改成半同步接口呢，还是说就是tutorial里的例子呢？（因为trpc和srpc是没有区别的，只有协议格式不一样，如果目前没有发现内存增长，可能就是随机性的）
2. 因为我没有windows的环境，方便帮我们试试workflow下的tutorial么？其中tutorial-00可以编译出http server，tutorial-01是发起http请求的wget，可以按你上述的习惯改成循环发送，类似写法：
~~~cpp
    while (1)                                                                   
    {                                                                           
        protocol::HttpRequest req;                                                                                       
        req.set_method(HttpMethodGet);                                          
        req.set_http_version("HTTP/1.1");                                       
        req.set_request_uri("/");                                               
        req.set_header_pair("Host", "http://127.0.0.1:8888");                   
        req.add_header_pair("Connection", "keep-alive");                                                         
        auto future = WFFacilities::async_request<protocol::HttpRequest, protocol::HttpResponse>(TT_TCP, "http://127.0.0.1:8888", std::move(req), 0);
        auto res = future.get();                                                
        std::cout<< "task state:" << res.task_state << std::endl;               
    } 
~~~

**Comment by j05070415** [comment]
第一个问题，代码都一样，只是换了下TRPCServer和TRPCClient
第二个问题，相同写法，服务端和客户端程序内存正常，但是半双工发起HTTP请求经常返回失败，task state:1

**Comment by j05070415** [comment]
> 
![无标题](https://user-images.githubusercontent.com/7128724/189530933-71733da3-f06d-4077-8a74-907d6d86b332.png)

**Comment by j05070415** [comment]
> > 
> 
> ![无标题](https://user-images.githubusercontent.com/7128724/189530933-71733da3-f06d-4077-8a74-907d6d86b332.png)

服务端代码：
	unsigned short port = 8888;
	WFHttpServer server(process);
	//port = atoi(argv[1]);
	if (server.start(port) == 0)
	{
#ifndef _WIN32
		pause();
#else
		getchar();
#endif
		server.stop();
	}
客户端代码：
	while (1)
	{
		protocol::HttpRequest req;
		req.set_method(HttpMethodGet);
		req.set_http_version("HTTP/1.1");
		req.set_request_uri("/");
		req.set_header_pair("Host", "http://127.0.0.1:8888");
		req.add_header_pair("Connection", "keep-alive");
		auto future = WFFacilities::async_request<protocol::HttpRequest, protocol::HttpResponse>(TT_TCP, "http://127.0.0.1:8888", std::move(req), 0);
		auto res = future.get();
		std::cout << "task state:" << res.task_state << std::endl;
	}

**Comment by j05070415** [comment]
最好用虚拟机打个环境试试，有可能我这边哪没用对，或者环境库版本不对

**Comment by Barenboim** [comment]
你好，麻烦确认几个问题。您的workflow Windows版，是最新代码吗？我们vckpg上的代码非常的旧，最好直接clone windows分支的最新代码。
这个client代码可以运行，但我么的http一般是通过创建http任务来实现的。这个async_request不能实现http完整的功能。例如，client可以这么实现：
~~~cpp
void http_callback(WFHttpTask *task)
{
    std::cout << "task state:" << task->get_state() << std::endl;
    WFHttpTask *next = WFTaskFactory::create_http_task("http://127.0.0.1:8888", 0, 0, http_callback);
    series_of(task)->push_back(next);
}

int main()
{
    WFHttpTask *first = WFTaskFactory::create_http_task("http://127.0.0.1:8888", 0, 0, http_callback);
    first->start();
    getchar();  // wait here
    return 0;
}
~~~
我们这个async_request一般不是给内置协议用的。

**Comment by j05070415** [comment]
> 你好，麻烦确认几个问题。您的workflow Windows版，是最新代码吗？我们vckpg上的代码非常的旧，最好直接clone windows分支的最新代码。 这个client代码可以运行，但我么的http一般是通过创建http任务来实现的。这个async_request不能实现http完整的功能。例如，client可以这么实现：
> 
> ```c++
> void http_callback(WFHttpTask *task)
> {
>     std::cout << "task state:" << task->get_state() << std::endl;
>     WFHttpTask *next = WFTaskFactory::create_http_task("http://127.0.0.1:8888", 0, 0, http_callback);
>     series_of(task)->push_back(next);
> }
> 
> int main()
> {
>     WFHttpTask *first = WFTaskFactory::create_http_task("http://127.0.0.1:8888", 0, 0, http_callback);
>     first->start();
>     getchar();  // wait here
>     return 0;
> }
> ```
> 
> 我们这个async_request一般不是给内置协议用的。

workflow使用Windows分支后内存有变化但是能控制住，我再测试一晚上观察下

**Comment by Barenboim** [comment]
感谢感谢！麻烦都用最新代码试一下，包括srpc的。vcpkg我们维护得不太好，人手问题。

**Comment by holmes1412** [comment]
> 第二个问题，相同写法，服务端和客户端程序内存正常，但是半双工发起HTTP请求经常返回失败，task state:1

async_request里构造的http请求确实少了一层派生功能，state为1应该是机器连接数满了，对于这种情况确实建议使用series_of(task)->push_back(next);的写法，不是你的写法的问题。谢谢后面又帮我们试了。

> 第一个问题，代码都一样，只是换了下TRPCServer和TRPCClient

这个我目前也没有想明白，之后方便的话再帮对比试一下。感谢～

**Comment by j05070415** [comment]
> 
![无标题](https://user-images.githubusercontent.com/7128724/189554873-ae4bd2b9-5595-4108-83b8-e696d97b40ef.png)

使用SRPCServer和SRPCClient，测试一晚内存还是会涨到500M，测试代码不变

**Comment by holmes1412** [comment]
收到～谢谢，我明天找windows下的小伙伴帮复现一下～>_<

请问用workflow的http有这样的问题吗？
以及再试试trpc协议的server和client也会有这样的问题不？

**Comment by j05070415** [comment]
> 

1.我把srpc切到0.9.7版本，workflow使用windows最新分支，发下内存增长明细变慢；
2.另外，相同程序在另外一台电脑上，配置Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz   2.59 GHz，内存16GB，内存稳定在12M；在笔记本，测试有内存泄露电脑上，相同程序，内存初始4M，一小时后18M左右，电脑配置，i5-5200U  CPU @2.2GHz，内存8GB
我怀疑两点：
1.srpc最新版本可能有问题
2.低配置电脑易出现内存泄露

**Comment by j05070415** [comment]
> 

补充下，0.9.7在笔记本上测试，在两小时后内存又落回12M左右，所有0.9.7感觉测试内存比较稳定

**Comment by j05070415** [comment]
> 

补充下，我笔记本测试三小时发下内存稳定在43M左右，看样子没泄露，那是不是版本问题了

**Comment by holmes1412** [comment]
收到，辛苦小伙伴详细的测试～我也已经联系windows的小伙伴了，有空了他会帮看看。如果还有什么发现，或者如果windows有valgrind之类的定位工具提供新的信息的话，都非常欢迎继续反馈！
