### ISSUE TITLE
client端访问status code 103

### ISSUE THREAD

**Issue by whiker92** [sogou/srpc#280]
![image](https://user-images.githubusercontent.com/13618283/217714062-9b592d97-e7b1-44fe-b31d-c7e45a590795.png)
写了一个简单的client，终端输入url时都没有问题，但输入方式变成了管道后(cat data.txt | ./client) ，开始返回status code 103了

**Comment by holmes1412** [comment]
你好，103在srpc框架是RPCStatusProcessTerminated，表示程序终止或退出。这里用了Get的异步接口，如果是cin的话，文件输入完main函数就退出了，就等不到这个lambda被callback了。
可以用一些计数器租塞在读完输入之后，比如：
```cpp
while (cin >> s) {
   ...
}
wait_group.wait();
```
或者使用counter进行更加准确的退出控制。
