### ISSUE TITLE
"无公网IP的srpc_pb_server" 同 " 有公网IP的srpc_pb_client "如何实现rpc调用？

### ISSUE THREAD

**Issue by GreenValue** [sogou/srpc#29]
背景：GPU的云服务器太贵，故在公司局域网内部署了一台GPU。
问题： 云端的程序（“ srpc_pb_client有外网IP”），能用srpc 调用该GPU（ srpc_pb_server无外网IP）吗？

文件名来自srpc/tutorial里面：
 srpc_pb_client
 srpc_pb_server

**Comment by Barenboim** [comment]
能不能搞个vpn什么的，感觉这是一个通用问题，和srpc没有什么关系。

**Comment by GreenValue** [comment]
有vpn介入，性能应该会下降。
我的拙见是：
①client通过srpc发起一个A请求
②server收到A请求后，不着急回复，直到有需要的时候，回复B，B中的内容是让client进行计算；
③client收到B回复后，进行计算，再发起A请求（此时A请求中有计算结果）；
然后server再继续①。
虽然很别扭，但可行吗？

**Comment by Barenboim** [comment]
我想了想你的方法居然是可行的，在server的process里用一个counter把series堵住，需要发请求的时候通过count_by_name(1)打开一个counter，counter的callback里填写的内容就是要发的请求。然后这时候client的请示收到回复，但这个回复其实是server发来的请求，由于client再发一个请求过去，其实是个response：）当然有几个超时你可能需要配置成-1，要不然连接关闭了process端就无法发消息出去了。
server的process除第一个握手请求之外，收到的其实是一个response，那么你需要手动把request对应上，方法肯定有。
但我觉得这个方法实在是有点复杂，必须把workflow用得很熟才可以。

**Comment by GreenValue** [comment]
感谢。
