### ISSUE TITLE
关于压缩的问题

### ISSUE THREAD

**Issue by James-Moriarty** [sogou/srpc#296]
看了下项目中有关压缩的介绍，没有太理解具体的用法，如果是以下几种情况，是否可正常请求？

1. server端设置了压缩方式，client在task没有设置压缩方式
2. server端没有设置压缩，client在task中设置了压缩方式
3. server端设置了压缩方式，但是client在task设置的压缩方式和server不同

另外一个问题是：http接口（json）如何使用压缩？

**Comment by holmes1412** [comment]
都可以互通的，因为压缩和解压是srpc框架做的事情，开发者无需关心。

比如server设置了压缩，那么server的回包里srpc协议有个域标记了压缩方式，那么client收到之后srpc框架去自动解压，然后才把结果给到开发者。

HTTP的压缩方式设置到header上，业界常用是设置为Contend- Encoding。

**Comment by James-Moriarty** [comment]
nice，我尝试下，感谢
