### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ChengYe9527** [sogou/srpc#297]
i try to use srpc/tools/srpc to make http,but it not work
<img width="639" alt="截屏2023-03-30 14 44 56" src="https://user-images.githubusercontent.com/80753628/228751801-a0c0a1e9-2b2c-4008-a81f-45e044224b15.png">

**Comment by ChengYe9527** [comment]
我应该怎么使用呢

**Comment by holmes1412** [comment]
你好，我执行这个命令是没有问题的。麻烦确认下是否使用最新的代码，另外可以告知一下具体的系统、cmake版本等信息吗？

**Comment by ChengYe9527** [comment]
是在docker下，ubuntu20.04
从github的srpc页面下载
git clone --recursive https://github.com/sogou/srpc.git
cd srpc
make
也装了protobuf3.6.1的版本，编译没有报错了

**Comment by ChengYe9527** [comment]
是有特定的安装路径吗？

**Comment by holmes1412** [comment]
和安装路径没有关系，这个小工具只是做简单的参数解析，还不涉及pb呢。我们也没遇到过这个问题，目前只能是怀疑getopt这个返回值在不同平台下有点不一样，需要等我找到类似的系统复现出来才能确定。

**Comment by holmes1412** [comment]
不涉及protobuf～

**Comment by holmes1412** [comment]
需要等我晚点找个环境复现一下。
你可以先把tools/srpc_basic_controller.cc的311、312行注释掉，313的return false改成return true，然后在tools目录下重新把srpc这个小工具编译出来看看，先感受下构建的用法🙏

**Comment by holmes1412** [comment]
是的，只有master分支有tools目录

**Comment by ChengYe9527** [comment]
有在macos上安装吗？openssl怎么解决？

**Comment by Barenboim** [comment]
mac上也测试过的。openssl我们默认已经安装，毕竟现场编译openssl还是太慢了。

**Comment by ChengYe9527** [comment]
> mac上也测过的。openssl我们默认已经安装，最终现场编译openssl还是太慢了。

openssl是什么版本呢？

**Comment by holmes1412** [comment]
@ChengYe9527 可以直接使用brew install openssl
具体可以参考：https://github.com/sogou/workflow/issues/150
注意macOS有自带的ssl，所以如果使用openssl的话，brew安装之后要按照它的提示建立链接。

**Comment by ChengYe9527** [comment]
<img width="553" alt="截屏2023-03-31 16 18 24" src="https://user-images.githubusercontent.com/80753628/229065800-10054886-94d5-42f7-9c2b-787c3ea7797f.png">
你好，我这边mac编译srpc报错

**Comment by holmes1412** [comment]
不确定是你原先没有安装protobuf还是系统找默认路径的不统一，建议你可以源码安装一下protobuf。

参考：

```
git clone -b 3.20.x https://github.com/protocolbuffers/protobuf.git protobuf.3.20
cd protobuf.3.20
sh autogen.sh
./configure
make -j4
make install
```

**Comment by ChengYe9527** [comment]
我装的 3.6

**Comment by ChengYe9527** [comment]
w

> 不确定是你最初没有安装protobuf还是系统找到默认路径的不均匀，建议你可以用源码安装一下protobuf。
> 
> 参考：
> 
> ```
> git clone -b 3.20.x https://github.com/protocolbuffers/protobuf.git protobuf.3.20
> cd protobuf.3.20
> sh autogen.sh
> ./configure
> make -j4
> make install
> ```
我装了protobuf还是报错

**Comment by ChengYe9527** [comment]
> 是源码安装了还报错了吗？可以把新的报错信息发给我看一下～

<img width="553" alt="截屏2023-03-31 17 49 34" src="https://user-images.githubusercontent.com/80753628/229087375-e052159a-9509-4dd1-b69e-d5a81f4a0d5d.png">

**Comment by kedixa** [comment]
@ChengYe9527 
你好，你的处理器是Arm的吗，发一下 cat /proc/cpuinfo | head -n 30 的输出

编译一下下面的代码，并把输出发一下
```cpp
#include <type_traits>
#include <iostream>

bool f() {
    return (char)-1 == (signed char)-1;
}
bool g() {
    return (char)-1 == (unsigned char)-1;
}

int main() {
    std::cout << f() << std::endl;
    std::cout << g() << std::endl;
    return 0;
}
```

**Comment by Barenboim** [comment]
修了：https://github.com/sogou/srpc/commit/d25cbfd72660474a29c71fb77e4f9f614e4c1e61

**Comment by Barenboim** [comment]
https://github.com/sogou/srpc/pull/298

**Comment by ChengYe9527** [comment]
> cat /proc/cpuinfo | head -n 30

cat: /proc/cpuinfo: No such file or directory


代码输出


1
0

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Barenboim** [comment]
最新代码应该已经修复问题了！感谢。

**Comment by ChengYe9527** [comment]
又在M1的mac上试过吗


> 是源代码安装了还报错了吗？可以把新的报错信息发给我看一下～

**Comment by holmes1412** [comment]
@ChengYe9527 是的是一个getopt返回值原先我处理没有很细心的问题，已经修复了。麻烦再试一下，可以用你一开始的ubuntu20.04试试
