### ISSUE TITLE
New versions of GTest use C++14

### ISSUE THREAD

**Issue by bkmgit** [sogou/srpc#303]
Might it be possible to add a change similar to:
https://github.com/sogou/workflow/pull/1188/files
to enable using newer versions of GTest, current build fails:
https://download.copr.fedorainfracloud.org/results/fed500/srpc/fedora-rawhide-x86_64/05796491-srpc/builder-live.log.gz
Can do this if ok.

**Comment by holmes1412** [comment]
Yes, I will add similar changes to fix this failing build.
Thanks.

**Comment by holmes1412** [comment]
@bkmgit It would be very appreciated if you could check that this commit works.

repo and branch: https://github.com/holmes1412/srpc/tree/cmake-3.26

**Comment by bkmgit** [comment]
谢谢 Based on https://github.com/holmes1412/srpc/pull/33 it seems to run. When testing get
```
[----------] 1 test from ThriftHttp
[ RUN      ] ThriftHttp.unittest
/workflow/test/unittest.cc:165: Failure
Expected equality of these values:
  ctx->success()
    Which is: false
  true
[  FAILED  ] ThriftHttp.unittest (0 ms)
[----------] 1 test from ThriftHttp (0 ms total)
```
Other tests pass. This test passes locally for me though.

**Comment by holmes1412** [comment]
I can't figure out why it fails here. Could you post the failing link or some more informations?

**Comment by bkmgit** [comment]
https://github.com/bkmgit/srpc/actions/runs/4728630404/jobs/8390349320

Will continue debugging though if not immediately clear. Maybe setup, tests are not running on Ubuntu CI.

**Comment by holmes1412** [comment]
Thanks! I will try the ci actions like you do in the test branch and fix this failing UnitTest tomorrow.

**Comment by bkmgit** [comment]
Test seems to pass now on both Ubuntu and Fedora, maybe was an issue with GitHub:
https://github.com/bkmgit/srpc/actions/runs/4739468284/jobs/8414324683
Can update and rebase https://github.com/holmes1412/srpc/pull/33 if helpful

**Comment by holmes1412** [comment]
Already merged~ Glad the test passed and thank you so much for the effort in checking the builds on Ubuntu and Fedora. It's helpful of course. 
We'll deal with the PR https://github.com/sogou/srpc/pull/304 and make a released version.
