### ISSUE TITLE
srpc_generator.exe无法使用

### ISSUE THREAD

**Issue by yourlife-mylife** [sogou/srpc#332]
在Win10中，在编译tutorial中的示例程序时，无法自动生成echo_pb.srpc.h文件，手动使用命令“srpc_generator protobuf echo_pb.proto”也不能生成echo_pb.srpc.h等文件。确定srpc_generator 已添加环境变量，可以找到srpc_generator .exe。

**Comment by holmes1412** [comment]
你好，windows我们没有调试环境，都是靠各位开发者帮提议支持的。

windows应该是解析参数部分和linux不太一样，但应该是更简单的旧版做法。

麻烦能不能贴一下执行命令之后屏幕打印的内容？如果可以的话可以帮我们debug一下，主要就是一个代码解析，在src/generator/目录下下，主要是compiler.cc和parser.cc。

**Comment by yourlife-mylife** [comment]
> 你好，windows我们没有调试环境，都是靠各位开发者帮提议支持的。
> 
> windows应该是解析参数部分和linux不太一样，但应该是更简单的旧版做法： https://github.com/sogou/srpc/blob/master/src/generator/compiler.cc#L78
> 
> 麻烦能不能贴一下执行命令之后屏幕打印的内容？如果可以的话可以帮我们debug一下，主要就是一个代码解析，在src/generator/目录下下，主要是compiler.cc和parser.cc。

已经定位到问题所在，compiler.cc文件第69行，if (parse_origin(argc, argv, params, idl_type) == 0)应该改成if (parse_origin(argc, argv, params, idl_type) != 0)

**Comment by holmes1412** [comment]
感谢！太给力了！可以给我们直接发一个Pull Request吗？
