### ISSUE TITLE
Android compile problem

### ISSUE THREAD

**Issue by ouclbc** [sogou/srpc#336]
when I config android cross compile,and build srpc, I met the following error
workflow/_include/workflow/Communicator.h:28:10: fatal error: 'openssl/ssl.h' file not found
since android ndk has no openssl,How can I config this?
I try to do this:https://segmentfault.com/a/1190000004522943
but seems I build 64 bit so.

**Comment by ouclbc** [comment]
指定openssl include和so路径后，报错如下：
/home/Android/srpc/workflow/src/manager/WFGlobal.cc:566:16: error: use of undeclared identifier 'getline'; did you mean 'std::getline'?
        while ((ret = getline(&line, &bufsize, fp)) > 0)
                      ^~~~~~~
                      std::getline
/home/Android/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/string:4244:1: note: 'std::getline' declared here
getline(basic_istream<_CharT, _Traits>& __is,
^
/home/Android/srpc/workflow/src/manager/WFGlobal.cc:566:16: error: no matching function for call to 'getline'
        while ((ret = getline(&line, &bufsize, fp)) > 0)
                      ^~~~~~~
/home/barton/Android/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/string:4244:1: note: candidate template ignored: could not match 'basic_istream<type-parameter-0-0, type-parameter-0-1>' against 'char **'
getline(basic_istream<_CharT, _Traits>& __is,
^
2 errors generated.

**Comment by ouclbc** [comment]
改成std::getline提示参数不匹配。只有2个参数，实际传了三个。

**Comment by holmes1412** [comment]
我们看看先前能在Android上编译过的版本对比一下，看看是不是后来加的、是否需要替换掉这个函数。

**Comment by ouclbc** [comment]
thank you very much,想问一下你们之前在Android上面编译有文档么？

**Comment by holmes1412** [comment]
https://github.com/sogou/workflow/issues/773
原先有一个人在Android上编译过Workflow，写了个很详细的总结，可以看看这个～
另外确认了下commit log，当时已经是这样使用的`getline`了，但是他没有遇到这样的问题。你如果还没有解决，可以到这个issue下圈他问问。

**Comment by ouclbc** [comment]
目前workflow android可以编译通过，srpc还不行。
system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1l"

**Comment by holmes1412** [comment]
感觉这个是OPENSSL_CRYPTO_LIBRARY缺少了，你尝试一下手动指定一下？比如
set(OPENSSL_CRYPTO_LIBRARY /path/to/openssl/lib/libcrypto.a)

不过这个crypto包workflow也需要，感觉crypto本身不应该有区别才是～

**Comment by ouclbc** [comment]
再请教一下protobuf_generate_cpp这个是调用本机的protoc的么，而非host的，目前我指定的protobuf dir是host主机的，不知道这块怎么设置

**Comment by holmes1412** [comment]
protobuf_generate_cpp会由CMake 自动查找 protoc 工具的路径。CMake 会首先查找系统路径，如果找不到，则会查找 PROTOBUF_PROTOC_EXECUTABLE 变量指定的路径。如果 PROTOBUF_PROTOC_EXECUTABLE 变量未设置，则会使用默认路径 /usr/bin/protoc。

这个得看你find_package(protobuf)用的是哪个路径，需要libprotobuf.so和protoc版本对应。如果这里不确定，要不你手动指定一下`set (PROTOBUF_PROTOC_EXECUTABLE /xxx/xxx/protoc)`
让它们对应起来试试看？

**Comment by ouclbc** [comment]
https://blog.csdn.net/gcs_20210916/article/details/123919119这个链接有说明，不过目前试了效果还是提示package找不到，我再看看

**Comment by ouclbc** [comment]
手动指定，如下方式，还是提示unknown command protobuf_generate_cpp
set (PROTOBUF_PROTOC_EXECUTABLE /home/barton/work/protobuf-3.14.0/src)
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS ${PROTO_LIST})
参考这个文章，https://blog.csdn.net/gcs_20210916/article/details/123919119 也不太行。
目前看就是找不到protoc的路径。

**Comment by holmes1412** [comment]
试试set (PROTOBUF_PROTOC_EXECUTABLE /home/barton/work/protobuf-3.14.0/src/protoc) ?

**Comment by ouclbc** [comment]
参考这个https://blog.csdn.net/lnwaycool/article/details/102685354 可以编译过去了
SET(Protobuf_INCLUDE_DIR /usr/local/protobuf/include/)
SET(Protobuf_LIBRARY /usr/local/protobuf/lib/)
但是在编译compress的时候提示
src/message/CMakeFiles/message.dir/build.make:61: *** target pattern contains no '%'.  Stop
这个好像是空格引起的，但是没有定位到哪一个make file文件

**Comment by holmes1412** [comment]
虽然不太了解Android下的依赖应该怎么写，但是看了下当时workflow支持Android的时候，cmake文件里都进行了如下改动：
https://github.com/sogou/workflow/blob/master/src/CMakeLists.txt
1、编译时，依赖库通过交叉编译指定的路径
```cmake
if(ANDROID)
	include_directories(${OPENSSL_INCLUDE_DIR})
	link_directories(${OPENSSL_LINK_DIR})
else()
	find_package(OpenSSL REQUIRED)
endif ()
```
2、链接时，依赖库需要明确指定一下：
```cmake
if(ANDROID)
	target_link_libraries(${SHARED_LIB_NAME} ssl crypto c)
else()
	target_link_libraries(${SHARED_LIB_NAME} OpenSSL::SSL OpenSSL::Crypto pthread)
endif ()
```

要不你试试把这里：https://github.com/sogou/srpc/blob/master/src/CMakeLists.txt#L154 模仿Workflow里的写法？比如（但不一定正确，需要你在环境里调一下）

```cmake
if (APPLE)
    target_link_libraries(${SHARED_LIB_NAME} OpenSSL::SSL  OpenSSL::Crypto pthread protobuf workflow z ${SNAPPY_LIB} ${LZ4_LIB})
if (ANDROID) # 写法不一定正确，大概这么个想法？
    target_link_libraries(${SHARED_LIB_NAME} ssl crypto c protobuf workflow z snappy)
else ()
    target_link_libraries(${SHARED_LIB_NAME})
endif ()
```

**Comment by ouclbc** [comment]
修改的文件如下：
srpc下面的gnumakefile:
elseif(ANDROID)
ANDROID_NDK_HOME :=ndk的绝对路径
ANDROID_ABI_ARCH :=arm64
ANDROID_ABI :=arm64-v8a
ANDROID_API_LEVEL :=29
OPEN_SSL_DIR :=编译的openssl绝对路径
cd $(BUILD_DIR) && $(CMAKE3) -DANDROID_ABI=${ANDROID_ABI} -DANDROID_PLATFORM=android-${ANDROID_API_LEVEL} -DANDROID_NDK=${ANDROID_NDK_HOME} -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake -DOPENSSL_INCLUDE_DIR=${OPEN_SSL_DIR}/include -DOPENSSL_LINK_DIR=${OPEN_SSL_DIR} $(ROOT_DIR)
workflow也是上面类似修改
另外srpc里面的message和module模块也需要修改
if(ANDROID)
		SET(Protobuf_INCLUDE_DIR /home/XX/Android/protobuf-3.14.0/src)
		SET(Protobuf_LIBRARY /home/XX/Android/protobuf-3.14.0/cmake)
		find_package(Protobuf REQUIRED)
	endif()

**Comment by ouclbc** [comment]
另外请教一下，编译出so后，在编译sample的时候出现如下错误：
vendor/androidsrpcsample/include/srpc/rpc_message.h:30:7: error: 'srpc::RPCRequest' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
class RPCRequest
      ^
vendor/androidsrpcsample/include/srpc/rpc_message.h:45:35: warning: unused parameter 'seqid' [-Wunused-parameter]
        virtual void set_seqid(long long seqid) {}
                                         ^
vendor/androidsrpcsample/include/srpc/rpc_message.h:48:7: error: 'srpc::RPCResponse' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
class RPCResponse
      ^
vendor/androidsrpcsample/include/srpc/rpc_message.h:61:33: warning: unused parameter 'code' [-Wunused-parameter]
        virtual bool set_http_code(int code) { return false; }
                                       ^
vendor/androidsrpcsample/include/srpc/rpc_message.h:64:7: error: 'srpc::RPCMessage' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
class RPCMessage
这个虚函数应该是在其他模块里面实现的。

**Comment by holmes1412** [comment]
1. 感谢你的建议！方便的话可以把你的修改提一个PR给我们，这样在你的环境上 run过的比较能保证正确性。
2. 这个确实应该把基类的虚析构加上，我提个PR，review并merge了之后给你说，谢谢～

**Comment by ouclbc** [comment]
改动的东西比较零散，等我有空看看能不能整合成一个脚本

**Comment by ouclbc** [comment]
目前看srpc依赖的libcrypto和libssl以及libprotobuf和Android系统的有冲突，目前只能应用到apk里面。服务里面不可以。
