### ISSUE TITLE
MacOS下链接找不到protobuf

### ISSUE THREAD

**Issue by d976045024** [sogou/srpc#344]
<img width="806" alt="截屏2023-10-17 00 01 51" src="https://github.com/sogou/srpc/assets/62782300/cc97687f-6879-458d-b930-d52cfee6c796">
如图，试着按照教程安装了protobuf，仍然没有用，请问应该怎么解决

**Comment by holmes1412** [comment]
你好，可以把安装protobuf的步骤和路径发一下吗？

**Comment by d976045024** [comment]
protobuf通过源码安装没有成功，于是采用brew安装，安装后各路径如下(brew list protobuf)：
<img width="802" alt="image" src="https://github.com/sogou/srpc/assets/62782300/0feeca66-2434-4ed6-931a-d986082f3b16">
之后我修改了src目录下CMakeLists.txt，修改如下：
<img width="721" alt="image" src="https://github.com/sogou/srpc/assets/62782300/aa6cb792-1045-4a8d-99c8-953188d398f5">
<img width="662" alt="image" src="https://github.com/sogou/srpc/assets/62782300/2230d13d-ab8f-46bc-bf6a-87cb084cc081">

修改后没有报之前的错误，但是还是报了链接错误，具体如下：
<img width="979" alt="image" src="https://github.com/sogou/srpc/assets/62782300/33c9bbbf-6d7d-4e1b-b59f-4236076c079b">
<img width="974" alt="image" src="https://github.com/sogou/srpc/assets/62782300/01c5405b-dff1-491c-bf7d-ae38470caae1">

怀疑是不是protobuf版本或者库的添加路径不对。
大二小白非常感谢大佬能帮忙看一下

btw，按照文档在linux下可以正常编译运行, 看了下linux下protobuf位置在/usr/local/bin下，怀疑是不是没有设置软链。

**Comment by holmes1412** [comment]
可以尝试一下设置把set(Protobuf_LIB_DIR xxx) 改为set(Protobuf_LIBRARIES xxx) 再试一下吗？后者是官方文档里用的。

另外链接的时候，可以尝试强制指定lib，比如下面，src/CMakeLists.txt：
```
    if (APPLE)                                                                     
        target_link_libraries(${SHARED_LIB_NAME}                                   
                              OpenSSL::SSL                                         
                              OpenSSL::Crypto                                      
                              pthread                                              
                              protobuf ### 改成：/opt/homebrew/Cellar/protobuf/24.4/lib/libprotobuf.24.4.0.dylib                  
                              workflow                                             
                              z ${SNAPPY_LIB} ${LZ4_LIB})
    else ()                                                                        
        target_link_libraries(${SHARED_LIB_NAME})                                  
    endif ()
```
这样应该就不会链接到不一样的lib了。具体通用一点的改法我再定位一下，感谢～～

**Comment by d976045024** [comment]
你好，我根据你提到的继续改动了一下，现在执行make，链接似乎仍然会报错，执行进度略有不同，但报错信息相同，具体如下：
<img width="1058" alt="image" src="https://github.com/sogou/srpc/assets/62782300/16375ad0-7539-4b95-8fab-bf64b1f89ba0">
<img width="858" alt="image" src="https://github.com/sogou/srpc/assets/62782300/c0d0783c-8ecb-4bd4-8acd-8943b302a610">

我对整个项目目录做的所有改动如下：
1. 在根目录下的CMakeLists.txt做了以下改动：
<img width="912" alt="image" src="https://github.com/sogou/srpc/assets/62782300/720e60de-9b3f-4834-9b82-f3ed38ee1285">

2. 在src目录下的CMakeLists.txt做了以下改动：
<img width="895" alt="image" src="https://github.com/sogou/srpc/assets/62782300/7e456cd4-7b3d-48cd-b290-7e3a29403d90">
这里修改了protobuf需求版本，应该没有影响吧～不过也贴出来
<img width="426" alt="image" src="https://github.com/sogou/srpc/assets/62782300/6e190746-2e98-4c63-bb6a-5becab5f30b8">

<img width="765" alt="image" src="https://github.com/sogou/srpc/assets/62782300/2766ebd3-95dd-4430-9944-73304c6d3a44">

系统配置如下：APPLE M2 芯片
openssl也是通过homebrew安装，安装信息如下：
<img width="758" alt="image" src="https://github.com/sogou/srpc/assets/62782300/6ce28300-0a94-49b1-a29b-6c2127ac8490">
这里我没有按照官方文档中的要求添加到环境变量，请问下是否需要软链接到/usr/local/lib下，但是目前好像没有报openssl相关的错误

**Comment by holmes1412** [comment]
你的截图：set(Protobuf_LIBRARIES xxx)，这里应该需要指定的是lib的名字而不是路径，比如/opt/homebrew/Cellar/protobuf/24.4/lib/libprotobuf.24.4.0.dylib

刚才显示指定了cmake里这个lib的名字为${Protobuf_LIBRARIES}，PR是https://github.com/sogou/srpc/pull/345，你可以从我的fork上拉一份试试。P.S. 我看你的pb比较新，可以保留你的C++版本改到17那行，其他应该不需要改了。这样试试？

**Comment by holmes1412** [comment]
可以检查一下是否有可能先前安装的版本还在？你可以把变量打出来检查一下是否符合预期：
```
message(STATUS "Protobuf_VERSION : ${Protobuf_VERSION}")
message(STATUS "Protobuf_INCLUDE_DIRS : ${Protobuf_INCLUDE_DIRS}")
message(STATUS "Protobuf_LIBRARIES : ${Protobuf_LIBRARIES}")
message(STATUS "PROTOBUF_PROTOC_EXECUTABLE : ${PROTOBUF_PROTOC_EXECUTABLE}")
```

**Comment by d976045024** [comment]
终于成功啦！果然是忘记把之前的protobuf路径从zshrc里删除。谢谢！
另外，较新的代码好像需要c++14以上才能运行，CMakeLists.txt里指定的还是std=c++11，是不是该改一下

**Comment by d976045024** [comment]
终于成功啦！果然是忘记把之前的protobuf路径从zshrc里删除。谢谢！
另外，有个小建议，较新的代码好像需要c++14以上才能运行，CMakeLists.txt里指定的还是std=c++11，是不是该改一下

**Comment by Barenboim** [comment]
> 终于成功啦！果然是忘记把之前的protobuf路径从zshrc里删除。谢谢！ 另外，有个小建议，较新的代码好像需要c++14以上才能运行，CMakeLists.txt里指定的还是std=c++11，是不是该改一下

你可以自己改一下。
