### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Kiris-tingna** [sogou/srpc#35]
/usr/local/include/srpc/rpc_context.inl:119:60: 错误：对成员‘get_attachment’的请求有歧义
    return task_->get_resp()->get_attachment(attachment, len);

**Comment by Kiris-tingna** [comment]
workflow、srpc 是源码编译的

**Comment by holmes1412** [comment]
你好，我刚确认了下，是可以顺利编译的。想知道两个问题：
1. 你是在编译srpc框架的时候出的错，还是编译tutorial出的错？
2. 系统版本和gcc版本等细节可以告知一下吗？

**Comment by Barenboim** [comment]
好像是因为workflow的一个改动，出现了重名函数。我们看一下。

**Comment by Barenboim** [comment]
@Kiris-tingna 改好了，麻烦您再试一下。
