### ISSUE TITLE
在SRPCHttpServer上启用trace上报opentelemtry功能异常

### ISSUE THREAD

**Issue by archliu321** [sogou/srpc#363]
在SRPCHttpServer上启用trace功能时出core

**Comment by Barenboim** [comment]
有更详细的信息吗？

**Comment by archliu321** [comment]
现场：
通过srpc构建两个服务，一个SRPCServer、一个SRPCHttpServer，如下图
![image](https://github.com/sogou/srpc/assets/142767274/354fb3d7-2b91-4427-8464-ee698a04d39c)

现象：
（1）给SRPCServer的实例注入RPCTraceOpenTelemetry时，服务可以正常上报opentelemtry, 能收到http 200的回包。
（2）给SRPCHttpServer的实例注入RPCTraceOpenTelemetry时，服务上报opentelemtry时，直接出core。

**Comment by holmes1412** [comment]
你好，感谢反馈！已经定位问题了，是内部有个地方笔误导致的。我今天会修复完并提交代码。

两个协议的server区别是：SRPCServer上的trace功能公司内集群上报过ok，SRPCHttpServer上的trace功能是模仿前者做的模块，沿用了trace的模块，但新增了对HttpMessage的数据处理（为了兼容workflow的http），所以这个笔误就没有触发到。

**Comment by holmes1412** [comment]
@archliu321 你好，这个PR已经修改：https://github.com/sogou/srpc/pull/364，合并之后可以再试一下。
当前统计的内容除了trace链路的透传以外，其他task层面的信息还比较少。如果有具体信息需要上报，欢迎随时提需求。

**Comment by archliu321** [comment]
非常感谢支持，最新的代码已经可以用了，👏👏👏
