### ISSUE TITLE
关于 RPCBuffer 中 read_back 问题

### ISSUE THREAD

**Issue by zhang275** [sogou/srpc#369]
在 RPCBuffer 的 read_back 函数中，如果 offset 设置特别小，应该回退到头部处（即  cur_.first 指向 begin(), second为 0），然而此时状态为 cur_.first 指向 begin(), second为begin()->buflen；如果此时调用 fetch，那么获取的是第二个缓存块，逻辑上来说，应该是第一个缓存块吧。

**Comment by holmes1412** [comment]
感谢！太细心了！这里对第一个减到缓存块的边界处理是有问题的。

我们修正一下，如果你感兴趣也非常欢迎提一个PR~

**Comment by zhang275** [comment]
如果第一个 break 语句没有触发，并且此时又到达了 buffer_list_.begin()，那么此时 offset 是过小的，因此个人感觉只需加一句赋值即可

```
 		if (cur_.first == buffer_list_.begin())		
		{
			cur_.second = 0;                                   // add
			break;
		}
```

**Comment by holmes1412** [comment]
是的，这样可以修复。感兴趣可以提个PR哈
