### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [sogou/srpc#410]
Hi all,
This is Qianxin CodeSafe Team, we found a suspicious issue, at
https://github.com/sogou/srpc/blob/bb882f98820bff7fa91aa83b29640fa753e11772/src/http/http_task.cc#L414C6-L414C13
which has geting memory allocation at 

- https://github.com/sogou/srpc/blob/bb882f98820bff7fa91aa83b29640fa753e11772/src/http/http_task.cc#L414C6-L414C05
Line 415 exits, clearing the memory of the current class with the delete this statement.
However, in the current function, memory (405 lines) requested for pointer series is not freed, causing a leak.

**Comment by Barenboim** [comment]
Thank @QiAnXinCodeSafe 

The memory leak bug was confirmed and will be fixed soon.

**Comment by Barenboim** [comment]
Fixed: https://github.com/sogou/srpc/pull/405

**Comment by Barenboim** [comment]
Fixed: https://github.com/sogou/srpc/pull/411
