### ISSUE TITLE
Thrift IDL自动生成的skeleton代码相关修复

### ISSUE THREAD

**Issue by holmes1412** [sogou/srpc#50]
各位小伙伴，srpc会根据IDL文件自动生成两份代码：
- 如果IDL是protobuf，会生成``server.pb_skeleton.cc``和``client.pb_skeleton.cc``;
- 如果IDL是thrift，会生成``server.thrift_skeleton.cc``和``client.thrift_skeleton.cc``;

原生成的代码里thrift部分有误，会默认启动``SRPCServer``和``SRPCClient``，已经改成默认启动ThriftFramed协议的``ThriftServer``和``ThriftClient``了，main()函数如下：
```cpp
int main()
{
    unsigned short port = 1412;
    ThriftServer server; // 这里已修改为默认启动ThriftFramed协议的server

    ExampleServiceImpl example_impl;
    server.add_service(&example_impl);

    server.start(port);
    wait_group.wait();
    server.stop();
    return 0;
}
```
SRPC的Thrift Framed server/client可以和原生的其他语言的thrift互通，使用非常方便，欢迎大家尝试～

**Comment by Barenboim** [comment]
这个修改只是影响框架代码的默认协议，不是正确性修改。原来的框架代码产生的是SRPC协议，thrift IDL的service。新框架代码产生的就是Thrift framed binary协议的server与client，可以与其它语言thrift框架通信。
