### ISSUE TITLE
为什么使用代码生成而不用反射实现？

### ISSUE THREAD

**Issue by FHfirehuo** [sogou/srpc#57]
以thrift为例，开发Java项目。使用代码生成的几个问题：
第一，要引入和java语言本身不相关的语言和文件是否增加了学习和使用成本。
第二，生成的代码结构不清晰，可读性不好。当然这部分代码可能并不需要使用者阅读，单直接放到项目里侵入性太高。
第三，服务端和客户端生成的代码糅合在一起，界限不清晰，容易增加使用者疑惑。

总体感觉对于使用人来来说，没用很好的便利性，反而可能增加项目的复杂度。不利于java端的人直接使用，需要有人指导。

**Comment by Barenboim** [comment]
我们设计的时候考虑的兼容其他rpc的协议与用法，包括brpc和thrift。所以只能用这样的方式。
