### ISSUE TITLE
srpc支持Windows 平台使用么？

### ISSUE THREAD

**Issue by Juno119** [sogou/srpc#58]
hi 您好，workflow支持Windows平台使用，且有专有的windows分支。srpc支持Windows平台使用么？

**Comment by Barenboim** [comment]
你好，是支持的。我们是唯一支持的windows平台的brpc：）

**Comment by Juno119** [comment]
👍感谢答复，win10 vs2019编译已经通过了。搭车请教一下，后续会考虑加入etcd的支持么？

**Comment by Barenboim** [comment]
Http2和grpc由于性能问题目前不是我们的重点。不过，我们框架是完全支持把一个其它框架的异步任务变成我们的异步任务，放入我们的任务流里实现无缝融合，具体可以参考workflow的这个文档[关于计数器](https://github.com/sogou/workflow/blob/master/docs/about-counter.md#server与其它异步引擎结合使用)。

**Comment by ZhangHuanSir** [comment]
能支持windows很不错，但是老是编译不成功，好不容易编译出srpc.lib集成到工程又各种莫名其妙的错误，无法使用，能不能支持一下vcpkg，傻瓜式编译，

**Comment by holmes1412** [comment]
> 能支持windows很不错，但是老是编译不成功，好不容易编译出srpc.lib集成到工程又各种莫名其妙的错误，无法使用，能不能支持一下vcpkg，进行傻瓜式编译

感谢提醒👍🏻我们负责windows的同学这周末会给srpc支持上vcpkg

**Comment by ZhangHuanSir** [comment]
哇！那太棒了，期待！谢谢！

**Comment by holmes1412** [comment]
@ZhangHuanSir 目前已经支持上vcpkg了～有需要的话可以尝试一下哦>_<
