### ISSUE TITLE
编译server.cc 报这个错

### ISSUE THREAD

**Issue by rjzou** [sogou/srpc#68]
Mac环境，编译命令
g++ -o server server.cc example.pb.cc -std=c++11 -lsrpc -I/usr/local/opt/openssl@1.1/include -lprotobuf

提示：

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by holmes1412** [comment]
你好，怀疑是安装环境的问题。麻烦先尝试一下编译tutorial目录试试里边的例子：
```sh
cd tutorial
make
```
tutorial可以直接编译和使用。主页上的example编译我这边再确认一下～感谢

**Comment by rjzou** [comment]
Mac 使用-Isrpc 不够呢

**Comment by Barenboim** [comment]
对的。mac下可能需要吧所有库都-l进去。比较麻烦。要不就自己模仿tutorial的cmake写一个。
